### ISSUE TITLE
[Bug] dbt_project.yml not found when dbt_deps=True in RenderConfig and dependencies are pre-installed

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/astronomer-cosmos#1052]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.4.3

### dbt-core version

1.7.16

### Versions of dbt adapters

dbt-sqlserver==1.7.4

### LoadMode

AUTOMATIC

### ExecutionMode

LOCAL

### InvocationMode

None

### airflow version

2.9.1

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### What happened?

Tasks intermittently fail with the below traceback

### Relevant log output

```python
[2024-06-14, 04:55:51 UTC] {logging_mixin.py:188} INFO - 04:55:51 Encountered an error:
[Errno 2] No such file or directory: '/opt/dbt/packages/codegen/dbt_project.yml'
[2024-06-14, 04:55:51 UTC] {logging_mixin.py:188} INFO - 04:55:51 Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 91, in wrapper
result, success = func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 76, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 169, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 198, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 245, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 271, in wrapper
ctx.obj["manifest"] = parse_manifest(
File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 1790, in parse_manifest
manifest = ManifestLoader.get_full_manifest(
File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 311, in get_full_manifest
loader = cls(
File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 262, in __init__
self.manifest.state_check = self.build_manifest_state_check()
File "/usr/local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 978, in build_manifest_state_check
with open(path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dbt/packages/codegen/dbt_project.yml'
```
```


### How to reproduce

Set dbt_deps to True in RenderConfig (default) and pre-install dependencies when building the Astro image

### Anything else :)?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Contact Details

_No response_

**Comment by tatiana** [comment]
@RNHTTR if the dependencies are pre-installed, then `dbt_deps` should be `False`, not true.
If this is true, Cosmos will attempt to run `dbt deps` in the scheduler, and this command requires the `dbt_project.yml` file to exist.

**Comment by RNHTTR** [comment]
Should Cosmos raise an exception that makes that obvious?
