### ISSUE TITLE
[Bug]  Airflow plugin for dbtdocs is broken for Azure blob storage

### ISSUE THREAD

**Issue by abhishekbhakat** [astronomer/astronomer-cosmos#1084]
### Astronomer Cosmos Version

main (development)

### dbt-core version

1.7.2

### Versions of dbt adapters

dbt-core==1.7.2
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.4.4
dbt-snowflake==1.7.3

### LoadMode

AUTOMATIC

### ExecutionMode

AZURE_CONTAINER_INSTANCE

### InvocationMode

None

### airflow version

2.9.1

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### What happened?

Airflow is unable to read from Azure blob storage.
The code for selecting the container name and blob key is incorrect:

https://github.com/astronomer/astronomer-cosmos/blob/3ff8d1042ceb1b98999377e4caae788915fc1665/cosmos/plugin/__init__.py#L15-L19

Example blob URL: https://avitestremotelog.blob.core.windows.net/airflow-logs/config
Here, the format is `https://<storageaccount>.blob.core.windows.net/<containername>/<blobkey>`

The function `read_file()` can read only 1 file at a time. So if the plugin needs to read the index file, for a given env `AIRFLOW__COSMOS__DBT_DOCS_DIR` as `wasb://somestorageaccountname.blob.core.windows.net/somecontainername/someprefix`
 then the invocation should something like:

```python
hook.read_file(container_name="somecontainername",blob_name="someprefix/index.html")
```

### Relevant log output

```shell
[2024-07-08T07:25:20.955+0000] {app.py:1744} ERROR - Exception on /cosmos/dbt_docs_index.html [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/fab/auth_manager/decorators/auth.py", line 117, in decorated
    return _has_access(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/www/auth.py", line 163, in _has_access
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/plugin/__init__.py", line 172, in dbt_docs_index
    html = open_file(op.join(docs_dir, "index.html"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/plugin/__init__.py", line 79, in open_file
    return open_azure_file(conn_id=conn_id, path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/plugin/__init__.py", line 54, in open_azure_file
    content = hook.read_file(container_name=container, blob_name=blob)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 402, in read_file
    return self.download(container_name, blob_name, **kwargs).content_as_text()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 446, in download
    return blob_client.download_blob(offset=offset, length=length, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/storage/blob/_blob_client.py", line 905, in download_blob
    return StorageStreamDownloader(**options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/storage/blob/_download.py", line 366, in __init__
    self._response = self._initial_request()
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/storage/blob/_download.py", line 462, in _initial_request
    process_storage_error(error)
  File "/usr/local/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
azure.core.exceptions.HttpResponseError: The specifed resource name contains invalid characters.
RequestId:d4de9668-601e-0065-7107-d1f141000000
Time:2024-07-08T07:25:20.9444317Z
ErrorCode:InvalidResourceName
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.
RequestId:d4de9668-601e-0065-7107-d1f141000000
Time:2024-07-08T07:25:20.9444317Z</Message></Error>
```

### How to reproduce

Set env as:
```
export AIRFLOW__COSMOS__DBT_DOCS_DIR=wasb://somestorageaccountname.blob.core.windows.net/somecontainername/someprefix
export AIRFLOW__COSMOS__DBT_DOCS_CONN_ID=an_azure_wasb_connection

### Anything else :)?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Contact Details

abhishek.bhakat@astronomer.io

**Comment by abhishekbhakat** [comment]
I see the docs specifically mentions the wasb pattern `AIRFLOW__COSMOS__DBT_DOCS_DIR="wasb://my-container/path/to/docs"`. Closing the issue.
