### ISSUE TITLE
[Bug] Cosmos operator hanging to run dbt command and eventually timing out

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#1089]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.4.3

### dbt-core version

Any

### Versions of dbt adapters

Any

### LoadMode

AUTOMATIC

### ExecutionMode

LOCAL

### InvocationMode

None

### airflow version

Any

### Operating System

N/A

### Deployment

Other

### What happened?

Issue reported in the[ #airflow-dbt ](https://apache-airflow.slack.com/archives/C059CC42E9W/p1720553923050549)Slack by Sebastian Vargas:
> Hi,
> I have a dbt macro, when I execute dbt run-operation macro_name in terminal the process takes 2 minutes, but when I use DbtRunOperationOperator in airflow using cosmos, the process never ends. Someone knows how to fix that? I'm missing something? The version that i'm using is astronomer-cosmos[dbt.all]==1.4.2 . Thanks!

### Relevant log output

```shell
The logs:

[2024-07-09, 18:20:01 UTC] {subprocess.py:73} INFO - Running command: ['/usr/local/bin/dbt', 'run-operation', 'update_user_permissions', '--project-dir', '/tmp/tmp1ooz7acr', '--profiles-dir', '/tmp/tmp4lp5n493', '--profile', 'redshift_profile', '--target', 'dev']
[2024-07-09, 18:20:01 UTC] {subprocess.py:84} INFO - Command output:
[2024-07-09, 18:20:04 UTC] {subprocess.py:94} INFO - [0m18:20:04  Running with dbt=1.8.3
[2024-07-09, 18:20:05 UTC] {subprocess.py:94} INFO - [0m18:20:05  Registered adapter: redshift=1.8.1
[2024-07-09, 18:20:05 UTC] {subprocess.py:94} INFO - [0m18:20:05  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-07-09, 18:20:16 UTC] {subprocess.py:94} INFO - [0m18:20:16  Found 289 models, 3 operations, 36 data tests, 204 sources, 1243 macros
[2024-07-09, 18:45:01 UTC] {timeout.py:68} ERROR - Process timed out, PID: 16326
[2024-07-09, 18:45:01 UTC] {subprocess.py:111} INFO - Sending SIGINT signal to process group
[2024-07-09, 18:45:01 UTC] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/base.py", line 264, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 487, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 333, in run_command
    result = self.invoke_dbt(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 246, in run_subprocess
    subprocess_result: FullOutputSubprocessResult = self.subprocess_hook.run_command(
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/hooks/subprocess.py", line 90, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/usr/local/lib/python3.11/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 16326
[2024-07-09, 18:45:01 UTC] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=redshift_set_user_permissions, task_id=set_redshift_permissions, execution_date=20240709T122000, start_date=20240709T182001, end_date=20240709T184501
[2024-07-09, 18:45:01 UTC] {standard_task_runner.py:104} ERROR - Failed to execute job 536820 for task set_redshift_permissions (Timeout, PID: 16326; 16326)
[2024-07-09, 18:45:01 UTC] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-09, 18:45:01 UTC] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

The user reported:
> the process is ended by timeout (after 30 mins) but in dbt terminal this takes only 2 minutes

**Comment by tatiana** [comment]
I advised the user to confirm if the issue still happens if you use InvocationMode.DBT_RUNNER:
https://astronomer.github.io/astronomer-cosmos/getting_started/execution-modes.html#invocation-modes

I believe he may be having this issue due to a deadlock: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait

We could try setting `close_fds=True` in the [code](https://github.com/astronomer/astronomer-cosmos/blob/1f276384da7c165f943ef5df32a550a48dff61a5/cosmos/hooks/subprocess.py#L75) or switching to use [Popen.communicate](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate) - which is probably the safest [given Python's docs](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate):
> Warning Use [communicate()](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate) rather than [.stdin.write](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.stdin), [.stdout.read](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.stdout) or [.stderr.read](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.stderr) to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.

Ideally we'd reproduce this issue, but if we're unable, I believe we should create an early alpha release and check with the reporter of the issue if the bug is solved.

**Comment by tatiana** [comment]
Updates from Sebastian Vargas:

> I tried with the latest version of cosmos (1.5) but the problem persists. I'm using dbt inside airflow like this configuration https://astronomer.github.io/astronomer-cosmos/getting_started/astro.html

> The astro version that I'm using is FROM [quay.io/astronomer/astro-runtime:9.7.0](http://quay.io/astronomer/astro-runtime:9.7.0) , dbt version is dbt-redshift==1.8.1

> Also I tried with InvocationMode.DBT_RUNNER  and still having same issue

> reviewing the logs what I am seeing is that the process is executing a block of queries (grant) one by one instead of doing it in block and that is why it is taking so long compared to executing it from terminal


> I fixed adding "BEGIN" and "COMMIT" in the SQL to avoid cosmos execute sql one by one but that's weird because in terminal without that the macro runs in 2 minutes
```
BEGIN;
-- SQL#1
-- SQL#1
...
-- SQL#n
COMMIT;
```

**Comment by tatiana** [comment]
The fact that the issue was the same with `InvocationMode.DBT_RUNNER` shows that it is not a  Python subprocess problem since we're invoking the dbt commands using dbt as a library without the overhead of creating a new process.

I asked the bug reporter the following:
> Without this change to the SQL that fixed the problem, what happens if you try to run the same dbt query in Airflow with the BashOperator?

**Comment by tatiana** [comment]
This issue has been open for over a year without further conclusions, and it occurred with older versions of both Cosmos and dbt. We were not able to reproduce. Since there are no further details and actions, I'm closing it. Should this become an issue again, we can always create a new ticket.
