### ISSUE TITLE
[Bug] Airflow 2.10 compatibility

### ISSUE THREAD

**Issue by ms32035** [astronomer/astronomer-cosmos#1161]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.5.1

### dbt-core version

1.8.5

### LoadMode

DBT_LS_MANIFEST

### ExecutionMode

KUBERNETES

### InvocationMode

None

### airflow version

2.10.0

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Official Apache Airflow Helm Chart

### What happened?

Dag parsing fails with error

`Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/cosmos/operators/base.py", line 361, in __init__
    self.full_refresh = full_refresh
    ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1198, in __setattr__
    if key in self.__init_kwargs:
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'DbtRunLocalOperator' object has no attribute '_BaseOperator__init_kwargs'`

### How to reproduce

Install Airflow 2.10

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pankajastro** [comment]
Feel free to submit a PR whenever you're ready. I'm happy to review and merge it.

**Comment by pankajastro** [comment]
It looks like a side effect of the changes in PR https://github.com/apache/airflow/issues/41085. A quick workaround is to add the missing `__init__` method, which I have added in https://github.com/astronomer/astronomer-cosmos/pull/1162. Let's see how CI feel.

**Comment by dwreeves** [comment]
@pankajastro I am wondering if that is the best fix, or if that even works at all (if it does work, it will only work due to opaque MRO trickery).

I think the best solution is just that `super().__init__(**kwargs)` needs to be at the top of the `AbstractDbtBaseOperator` init call instead of at the bottom.

The error occurs inside the `__setattr__` for the `BaseOperator`. If you look at the `BaseOperator` code in 3.10, the issue is that the first thing the `__init__()` does is set the `__init_kwargs` and every other `__setattr__` beyond that assumes the existence of `self.__init_kwargs`.

(I'm personally not convinced this is appropriate and that this is a small bug in Airflow 2.10. 🤔)

**Comment by michael-robbins-seek** [comment]
Just following up with this? Is this a change required in Cosmos? Or some change in our usage of Cosmos required?

**Comment by tatiana** [comment]
We fixed this as part of https://github.com/astronomer/astronomer-cosmos/pull/1162, and this was released in Cosmos 1.7.0.
