### ISSUE TITLE
Airflow can't find dbt_project.yml

### ISSUE THREAD

**Issue by psascue** [astronomer/astronomer-cosmos#1185]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

Astro CLI Version: 1.28.1

### dbt-core version

1.7.18

### LoadMode

AUTOMATIC

### ExecutionMode

DOCKER

### InvocationMode

None

### airflow version

Airflow 2.10.0+astro.1

### Operating System

macOS Sonoma 14.4.1

### Deployment

Astronomer

### Deployment details

Using `astro dev start` to start dbt + Airflow with Docker

### What happened?

Airflow is showing this error when I try to add a test dag:
<img width="1403" alt="Screenshot 2024-09-01 at 6 52 46 PM" src="https://github.com/user-attachments/assets/9930e11e-b1ff-4b6d-9ff3-ccd88be77775">

The `profiles.yml` and `dbt_project.yml` is in `/dags/dbt/data_pipeline/`. Here's my directory structure:
<img width="184" alt="Screenshot 2024-09-01 at 7 00 59 PM" src="https://github.com/user-attachments/assets/5415a960-3743-49f5-881c-361227bc6a5c">

I am using my own `profiles.yml` for `ProfileConfig` as the target is to an Azure SQL DB. Here's the dag:
```python
import os
from datetime import datetime
from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig
from cosmos.config import ProfileConfig

profile_config = ProfileConfig(
    profile_name="al_data_warehouse",
    target_name="dev",
    profiles_yml_filepath="/usr/local/airflow/dags/dbt/data_pipeline/profiles.yml"
)

dbt_azsql_dag = DbtDag(
    project_config=ProjectConfig("/usr/local/airflow/dags/dbt/data_pipeline",),
    operator_args={"install_deps": True},
    profile_config=profile_config,
    execution_config=ExecutionConfig(dbt_executable_path=f"{os.environ['AIRFLOW_HOME']}/dbt_venv/bin/dbt",),
    schedule_interval="@daily",
    start_date=datetime(2023, 9, 10),
    catchup=False,
    dag_id="dbt_dag"
)
```

### Relevant log output

```shell
Broken DAG: [/usr/local/airflow/dags/dbt_dag.py]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 442, in run_dbt_ls
    stdout = run_command(ls_command, tmp_dir, env_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 156, in run_command
    raise CosmosLoadDbtException(f"Unable to run {command} due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/usr/local/airflow/dbt_venv/bin/dbt', 'ls', '--output', 'json', '--project-dir', '/tmp/tmpgp3qt0z3', '--profiles-dir', '/usr/local/airflow/dags/dbt/data_pipeline', '--profile', 'data_warehouse', '--target', 'dev'] due to the error:
[0m08:45:42  Running with dbt=1.7.18
[0m08:45:42  Encountered an error:
libodbc.so.2: cannot open shared object file: No such file or directory
```

### How to reproduce

1. Create new directory for astro
2. Ran `astro dev init`
3. Copy dbt project to `/dags/dbt/data_pipeline`
4. Ran `astro dev start`
5. Add `dbt_dag.py` as above
6. Check Airflow

### Anything else :)?

I have been running dbt manually for this project. This is my first time using Airflow and Cosmos, so this may not be a bug and just need a fix.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Contact Details

psascue@gmail.com

**Comment by tatiana** [comment]
@psascue, please could you which version of the `astronomer-cosmos` python package you're using? I noticed you added `Astro CLI Version: 1.28.1`, but that doesn't give us information on the version of Cosmos because it is not installed as part of the Astro Runtime or the Astro CLI.

**Comment by tatiana** [comment]
We never got additional information or data to reproduce the issue, so we are assuming ti was resolved.
