### ISSUE TITLE
[Bug] Support for task owners (1.6.0) can lead to very long, cryptic task/DAG owners

### ISSUE THREAD

**Issue by jmaicher** [astronomer/astronomer-cosmos#1194]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.6.0

### dbt-core version

1.8.6

### LoadMode

AUTOMATIC

### ExecutionMode

KUBERNETES

### InvocationMode

None

### airflow version

2.9.3

### Operating System

debian 12 (bookworm)

### Deployment

Official Apache Airflow Helm Chart

### What happened?

https://github.com/astronomer/astronomer-cosmos/pull/1082 added support for task owners:

https://github.com/astronomer/astronomer-cosmos/blob/1f1fc61e637a5e66b1de483200782a7088246261/cosmos/core/airflow.py#L28-L31

In line 31, we fall back to [`dag.owner`](https://github.com/apache/airflow/blob/9a5f27f6dc560dcf456cabb793a32a61eab98dea/airflow/models/dag.py#L1155-L1162):

```python
    @property
    def owner(self) -> str:
        """
        Return list of all owners found in DAG tasks.

        :return: Comma separated list of owners in DAG tasks
        """
        return ", ".join({t.owner for t in self.tasks})
```

While it kinda looks recursive, it's not because the props are evaluated eagerly and the current task is not yet added to the DAG. However, when there are multiple tasks, some of which have an owner, some of which don't, this creates wild task and DAG owners, which can ultimately lead to errors during DAG processing when it's written to the DB (type overflow). The relevant log output shows one example, which happened to us after upgrading to 1.6.0:

> , , airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , ,  ... (22228 characters truncated) ...  airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , airflow, , airflow'

### Relevant log output

```shell
{dagbag.py:654} ERROR - Failed to write serialized DAG: /opt/airflow/dags/repo/dags/dbt.py
    return self.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 642, in _serialize_dag_capturing_errors
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
    dag_was_updated = SerializedDagModel.write_dag(
    if session.scalar(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
[parameters: ({'is_active': True, 'last_parsed_time': datetime.datetime(2024, 9, 4, 17, 0, 9, 474189, tzinfo=Timezone('UTC')), 'owners': ', airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow', 'dag_dag_id': '****'}, {'is_active': True, 'last_parsed_time': datetime.datetime(2024, 9, 4, 17, 0, 9, 475482, tzinfo=Timezone('UTC')), 'owners': ', , airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , ,  ... (22228 characters truncated) ...  airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , airflow, , airflow', 'dag_dag_id': '****'})]
[SQL: UPDATE dag SET is_active=%(is_active)s, last_parsed_time=%(last_parsed_time)s, owners=%(owners)s WHERE dag.dag_id = %(dag_dag_id)s]
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(2000)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    raise sa_exc.PendingRollbackError(
    self._assert_active()
    return self._transaction._connection_for_bind(
(Background on this error at: https://sqlalche.me/e/14/9h9h) (Background on this error at: https://sqlalche.me/e/14/7s2a)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
(Background on this error at: https://sqlalche.me/e/14/9h9h) (Background on this error at: https://sqlalche.me/e/14/7s2a)
    raise sa_exc.PendingRollbackError(
[parameters: ({'is_active': True, 'last_parsed_time': datetime.datetime(2024, 9, 4, 17, 0, 9, 474189, tzinfo=Timezone('UTC')), 'owners': ', airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow', 'dag_dag_id': '***'}, {'is_active': True, 'last_parsed_time': datetime.datetime(2024, 9, 4, 17, 0, 9, 475482, tzinfo=Timezone('UTC')), 'owners': ', , airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , ,  ... (22228 characters truncated) ...  airflow, airflow, , , airflow, airflow, , airflow, , , airflow, airflow, , , airflow, airflow, , , airflow, airflow, , airflow, , airflow, , airflow', 'dag_dag_id': '****'})]
    return self.execute(
[SQL: UPDATE dag SET is_active=%(is_active)s, last_parsed_time=%(last_parsed_time)s, owners=%(owners)s WHERE dag.dag_id = %(dag_dag_id)s]
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(2000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    conn = self._connection_for_bind(bind)
    self._assert_active()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
       ^^^^^^^^^^^^^^^
    if session.scalar(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    return func(*args, **kwargs)
    dag_was_updated = SerializedDagModel.write_dag(
```

### How to reproduce

Remove changes in airflow.py und run `test_build_airflow_graph_with_after_each`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
