### ISSUE TITLE
[Bug] missing attribute 'DbtSourceGcpCloudRunJobOperator' in new executionMode GCP_CLOUD_RUN_JOB

### ISSUE THREAD

**Issue by anai-s** [astronomer/astronomer-cosmos#1276]
### Astronomer Cosmos Version

1.7.0

### dbt-core version

1.7.18

### Versions of dbt adapters

1.4.0

### LoadMode

DBT_LS_MANIFEST

### ExecutionMode

DOCKER

### InvocationMode

None

### airflow version

2.9.1

### Operating System

Windows 10

### Deployment

Google Cloud Composer

### What happened?

I tried the new executionMode GCP_CLOUD_RUN_JOB but it raised the following issue:

```
Broken DAG (dags/cosmos_cloud_run_dag.py):
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/cosmos/airflow/graph.py", line 258, in generate_task_or_group
    task_or_group = create_airflow_task(task_meta, dag, task_group=task_group)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/cosmos/core/airflow.py", line 29, in get_airflow_task
    Operator = getattr(module, class_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cosmos.operators.gcp_cloud_run_job' has no attribute 'DbtSourceGcpCloudRunJobOperator'
```

### How to reproduce

I followed the jaffle_shop example in cosmos-example repository and add some configurations to my DAG:

```
def run_dbt_project() -> None:
    start_task = EmptyOperator(task_id="start-dbt-project")
    end_task = EmptyOperator(task_id="end-dbt-project")

    dbt_task_group = DbtTaskGroup(
        group_id="dbt-group",
        # dbt/cosmos-specific parameters
        project_config=project_config,
        profile_config=profile_config_yml,
        execution_config=ExecutionConfig(
            execution_mode=ExecutionMode.GCP_CLOUD_RUN_JOB
        ),
        render_config=RenderConfig(
            load_method=LoadMode.DBT_MANIFEST,
            source_rendering_behavior=SourceRenderingBehavior.WITH_TESTS_OR_FRESHNESS,
            select=["+tag:tag1+"],
        ),
        operator_args={
            "emit_datasets": False,  # Example of how to not set inlets and outlets
            "project_id": GCP_PROJECT_ID,
            "region": GCP_LOCATION,
            "job_name": GCP_CLOUD_RUN_JOB_NAME,
        },
    )

    start_task >> dbt_task_group >> end_task


run_dbt_project()
```

### Anything else :)?

You should add GCP_CLOUD_RUN_JOB as executionMode

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tatiana** [comment]
@anai-s this is a bug, probably both features were introduced in the same Cosmos release and we missed this.
It should be a relatively small fix, would you be up for trying to contribute on this?

**Comment by anai-s** [comment]
@tatiana Yes I can try to submit a PR to fix the bug

**Comment by tatiana** [comment]
Thanks a lot, @anai-s !
