### ISSUE TITLE
[Bug] dbt ls throwing error 'mock_value' is not of type 'integer' (TrinoLDAPProfileMapping)

### ISSUE THREAD

**Issue by dwolfeu** [astronomer/astronomer-cosmos#1315]
### Astronomer Cosmos Version

1.7.1

### dbt-core version

1.8.8

### Versions of dbt adapters

dbt-trino==1.8.3

### LoadMode

AUTOMATIC

### ExecutionMode

LOCAL

### InvocationMode

None

### airflow version

2.10.2

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### Deployment details

I'm using podman-compose v1.0.6, rather than docker-compose. I access my local dbt project files using a volume mount.

### What happened?

The dag import fails. Looking at the logs (see below), the error is with `dbt ls`, which is using the mock profile and complaining that one of the fields (I guess `port`?) isn't an integer:

```
Runtime Error
  Credentials in profile "cosmos_trino_test", target "foobar" invalid: 'mock_value' is not of type 'integer'
```

### Relevant log output

```shell
[2024-11-12T05:18:13.234+0000] {processor.py:186} INFO - Started process (PID=29) to work on /opt/airflow/dags/cosmos_test_dag.py
[2024-11-12T05:18:13.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/cosmos_test_dag.py for tasks to queue
[2024-11-12T05:18:13.237+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/cosmos_test_dag.py
[2024-11-12T05:18:13.253+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.253+0000] {graph.py:470} INFO - Trying to parse the dbt project using dbt ls cache cosmos_cache__my_cosmos_dag...
[2024-11-12T05:18:13.261+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.261+0000] {graph.py:476} INFO - Cosmos performance: Cache miss for cosmos_cache__my_cosmos_dag
[2024-11-12T05:18:13.261+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.261+0000] {graph.py:528} INFO - Trying to parse the dbt project in `/opt/airflow/dags/dbt-project` using dbt ls...
[2024-11-12T05:18:13.263+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.263+0000] {graph.py:547} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dags/dbt-project/target/partial_parse.msgpack
[2024-11-12T05:18:13.294+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.294+0000] {config.py:336} INFO - Profile caching is enable.
[2024-11-12T05:18:13.295+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.295+0000] {base.py:241} INFO - Using mock values for profile cosmos_trino_test
[2024-11-12T05:18:13.296+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.296+0000] {config.py:323} INFO - Profile not found in cache storing and using profile: /tmp/cosmos/profile/b490773c0053757a18f71df7ec6aac92f98955ff4854af5a0934f18df640f2a6/profiles.yml.
[2024-11-12T05:18:13.297+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:13.297+0000] {graph.py:136} INFO - Running command: `/home/airflow/.local/bin/dbt deps --project-dir /tmp/tmpbl0bi9j0 --profiles-dir /tmp/cosmos/profile/b490773c0053757a18f71df7ec6aac92f98955ff4854af5a0934f18df640f2a6 --profile cosmos_trino_test --target foobar`
[2024-11-12T05:18:16.716+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:16.716+0000] {graph.py:136} INFO - Running command: `/home/airflow/.local/bin/dbt ls --output json --project-dir /tmp/tmpbl0bi9j0 --profiles-dir /tmp/cosmos/profile/b490773c0053757a18f71df7ec6aac92f98955ff4854af5a0934f18df640f2a6 --profile cosmos_trino_test --target foobar`
[2024-11-12T05:18:18.245+0000] {logging_mixin.py:190} INFO - [2024-11-12T05:18:18.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/cosmos_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/cosmos_test_dag.py", line 52, in <module>
    dag_cosmos_test = DbtDag(
                      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/dag.py", line 26, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 260, in __init__
    self.dbt_graph.load(method=render_config.load_method, execution_mode=execution_config.execution_mode)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 402, in load
    self.load_via_dbt_ls()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 461, in load_via_dbt_ls
    self.load_via_dbt_ls_without_cache()
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 580, in load_via_dbt_ls_without_cache
    nodes = self.run_dbt_ls(dbt_cmd, self.project_path, tmpdir_path, env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 442, in run_dbt_ls
    stdout = run_command(ls_command, tmp_dir, env_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 156, in run_command
    raise CosmosLoadDbtException(f"Unable to run {command} due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/home/airflow/.local/bin/dbt', 'ls', '--output', 'json', '--project-dir', '/tmp/tmpbl0bi9j0', '--profiles-dir', '/tmp/cosmos/profile/b490773c0053757a18f71df7ec6aac92f98955ff4854af5a0934f18df640f2a6', '--profile', 'cosmos_trino_test', '--target', 'foobar'] due to the error:
05:18:18  Running with dbt=1.8.8
05:18:18  [WARNING]: Deprecated functionality

User config should be moved from the 'config' key in profiles.yml to the 'flags' key in dbt_project.yml.
05:18:18  Encountered an error:
Runtime Error
  Credentials in profile "cosmos_trino_test", target "foobar" invalid: 'mock_value' is not of type 'integer'
[2024-11-12T05:18:18.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/cosmos_test_dag.py
```

### How to reproduce

[Main docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/)

Make changes to `docker-compose.yaml` as necessary, e.g. set a volume mount for your dbt project files. Add a requirements.txt:

```
apache-airflow-providers-trino
astronomer-cosmos
dbt-core
dbt-trino
```

Run `docker compose build`, then `docker compose up airflow-init` and then `docker compose up` (your mileage may vary). Then add this dag:

```python
import datetime
from cosmos import DbtDag, ProjectConfig, ProfileConfig
from cosmos.profiles import TrinoLDAPProfileMapping

project_config = ProjectConfig("/opt/airflow/dags/dbt-project")

trino_ldap_mapping = TrinoLDAPProfileMapping(
    conn_id = 'trino_connection',
    profile_args = {
        'database': 'dev',
        'schema': 'dbt_cosmos_test',
        'threads': 4
        },
    disable_event_tracking=True
)

profile_config = ProfileConfig(
    profile_name="cosmos_trino_test",
    target_name="foobar",
    profile_mapping = trino_ldap_mapping
)

dag_cosmos_test = DbtDag(
    project_config=project_config,
    profile_config=profile_config,
    schedule_interval=None,
    start_date=datetime.datetime(2023, 1, 1),
    catchup=False,
    dag_id="my_cosmos_dag",
    default_args={"retries": 2},
)
```

You don't actually need to add an Airflow connection `trino_connection` to reproduce the error.

### Anything else :)?

The really odd thing is that I had the same setup working last week.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by pankajkoti** [comment]
@dwolfeu Do you know what changed between when it was working for you last week and now?

Also, can you try creating a valid Trino connection and see if you still get this error? I am believing that when proper valid values are not provided, Cosmos uses mock values for them https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/dbt/graph.py#L555 (the default value for `render_config.enable_mock_profile` is `True`)

Looking forward to your response to debug this further.

**Comment by dwolfeu** [comment]
@pankajkoti Thanks for you very quick response.

_> Do you know what changed between when it was working for you last week and now?_
I added a custom `airflow.cfg`. I got the error `'mock_value' is not of type 'integer'` and so I removed the custom `airflow.cfg`, deleted the images and rebuilt everything, i.e. I went back to how it was before, but the error persisted. I've compared what I'm trying now to what I committed to the remote repository and I don't see any differences.

_> Also, can you try creating a valid Trino connection and see if you still get this error?_
I get the error whether or not I set the connection. I can see that the connection is okay because this dag works:

```python
import datetime
from cosmos import DbtDag, ProjectConfig, ProfileConfig
from cosmos.profiles import TrinoLDAPProfileMapping
from airflow import DAG
from airflow.operators.python_operator import PythonOperator

project_config = ProjectConfig("/opt/airflow/dags/dbt-project")

trino_ldap_mapping = TrinoLDAPProfileMapping(
    conn_id = 'trino_connection',
    profile_args = {
        'database': 'dev',
        'schema': 'dbt_cosmos_test',
        'threads': 4
        },
    disable_event_tracking=True
)

profile_config = ProfileConfig(
    profile_name='cosmos_trino_test',
    target_name='foobar',
    profile_mapping = trino_ldap_mapping
)

def print_stuff():
    print(trino_ldap_mapping.get_profile_file_contents(profile_name='cosmos_trino_test'))

dag_dbt_profile = DAG(
    'dbt_profile',
    schedule_interval=None,
)

task = PythonOperator(
    task_id='print_dbt_profile',
    python_callable=print_stuff,
    dag=dag_dbt_profile,
)
````

This is the output:

```python
config:
    send_anonymous_usage_stats: false
cosmos_trino_test:
    outputs:
        cosmos_target:
            database: dev
            host: trino.foo.bar
            method: ldap
            password: '{{ env_var(''COSMOS_CONN_TRINO_PASSWORD'') }}'
            port: 443
            schema: dbt_cosmos_test
            threads: 4
            type: trino
            user: ***
    target: cosmos_target
```

I thought that the mismatched target names – `target_name='foobar'` in `ProfileConfig` and `cosmos_target` in the printed output – might be the issue, but changing `target_name` to `cosmos_target` in `ProfileConfig` doesn't resolve the issue.

**Comment by dwolfeu** [comment]
I can resolve the issue by supplying a manifest:

```python
project_config = ProjectConfig(
    dbt_project_path="/opt/airflow/dags/dbt-project",
    manifest_path="/opt/airflow/dags/dbt-project/target/manifest.json"
    )
```

**Comment by tatiana** [comment]
An alternative to workaround the issue is to use `render_config=RenderConfig(enable_mock_profile=False)`

There is a bug in `TrinoLDAPProfileMapping`'s `mock_profile`.

This is the default `mock_profile`:
https://github.com/astronomer/astronomer-cosmos/blob/2b21f4cbcb82161e6e79c4b023c8e19b5285ba05/cosmos/profiles/base.py#L193C1-L215C28

We should add a custom mock_profile to Trino's Base class that sets the port as an integer. This should be a simple fix. @dwolfeu would you be able to submit a PR on this?

**Comment by dwolfeu** [comment]
Thank you @tatiana for the fix. Regarding a PR: I will take a look.

**Comment by dwolfeu** [comment]
@tatiana I have created a [PR](https://github.com/astronomer/astronomer-cosmos/pull/1322).
