### ISSUE TITLE
Ensure no environment variables are set to `None` before running the subprocess

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astronomer-cosmos#134]
If an env var is `None`, you can get this weird/obscure error (e.g. don't set a role with a snowflake connection):

```
[2023-02-08, 14:37:12 UTC] {subprocess.py:75} INFO - Running command: [‘/home/astro/.venv/dbt/bin/dbt’, ‘run’, ‘--project-dir’, ‘/usr/local/airflow/include/dbt/jaffle_shop’, ‘--models’, ‘customers’, ‘--profile’, ‘snowflake_profile’]
[2023-02-08, 14:37:12 UTC] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File “/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py”, line 336, in execute
    result = self.build_and_run_cmd(env=self.get_env(context))
  File “/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py”, line 261, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env)
  File “/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py”, line 219, in run_command
    result = self.subprocess_hook.run_command(
  File “/usr/local/lib/python3.9/site-packages/airflow/hooks/subprocess.py”, line 77, in run_command
    self.sub_process = Popen(
  File “/usr/local/lib/python3.9/subprocess.py”, line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File “/usr/local/lib/python3.9/subprocess.py”, line 1741, in _execute_child
    env_list.append(k + b’=' + os.fsencode(v))
  File “/usr/local/lib/python3.9/os.py”, line 810, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jlaneve** [comment]
I _think_ the solution here could just be removing env vars with value = `None` in the `get_env` function, but need to test it to be sure.

https://github.com/astronomer/astronomer-cosmos/blob/8072203a30333271af6e5087b53c5170ff9e26bf/cosmos/providers/dbt/core/operators.py#L138-L156

**Comment by MikeWallis42** [comment]
Looks like you also can't have integers... I can confirm that this was due to environment variables being set incorrectly coming from the connections piece.

```
[2023-02-13, 15:37:27 GMT] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators.py", line 344, in execute
    result = self.build_and_run_cmd(env=self.get_env(context))
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators.py", line 265, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators.py", line 221, in run_command
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1767, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/local/lib/python3.10/os.py", line 811, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not int
```
So all environment variables must be `str, bytes or os.PathLike` as stated.

It's probably best to do it as late as possible in the process so it's a one-off effort, perhaps just before calling the SubProcessHook.

https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/providers/dbt/core/operators.py#L207-L227
