### ISSUE TITLE
Enable kubernetes tests for dbt-core-1.8.x

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-cosmos#1344]
The Kubernetes test on dbt-core 1.8.x failing with error 
```
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/dev/dags/jaffle_shop_kubernetes.py", line 85, in <module>
    run_models = DbtTaskGroup(
                 ^^^^^^^^^^^^^
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/converter.py", line 261, in __init__
    self.dbt_graph.load(method=render_config.load_method, execution_mode=execution_config.execution_mode)
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/dbt/graph.py", line 406, in load
    self.load_via_dbt_ls()
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/dbt/graph.py", line 465, in load_via_dbt_ls
    self.load_via_dbt_ls_without_cache()
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/dbt/graph.py", line 582, in load_via_dbt_ls_without_cache
    self.run_dbt_deps(dbt_cmd, tmpdir_path, env)
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/dbt/graph.py", line 515, in run_dbt_deps
    stdout = run_command(deps_command, dbt_project_path, env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/dbt/graph.py", line 156, in run_command
    raise CosmosLoadDbtException(f"Unable to run {command} due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/home/runner/.local/share/hatch/env/virtual/astronomer-cosmos/Za_bFbg4/tests.py3.11-2.10/bin/dbt', 'deps', '--project-dir', '/tmp/tmpmgl76aiy', '--profiles-dir', '/tmp/cosmos/profile/bac3236c5c54391c6c2161433c02c661510cb1db5380f8399bdf27c662a462b2', '--profile', '***_profile', '--target', 'dev'] due to the error:
Traceback (most recent call last):
  File "/home/runner/.local/share/hatch/env/virtual/astronomer-cosmos/Za_bFbg4/tests.py3.11-2.10/bin/dbt", line 5, in <module>
    from dbt.cli.main import cli
  File "/home/runner/.local/share/hatch/env/virtual/astronomer-cosmos/Za_bFbg4/tests.py3.11-2.10/lib/python3.11/site-packages/dbt/cli/__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astronomer-cosmos/Za_bFbg4/tests.py3.11-2.10/lib/python3.11/site-packages/dbt/cli/main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "/home/runner/.local/share/hatch/env/virtual/astronomer-cosmos/Za_bFbg4/tests.py3.11-2.10/lib/python3.11/site-packages/dbt/cli/requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

In dbt codebase I can see module dbt.adapters.factory is available for only dbt < 1.8.x
CI: https://github.com/astronomer/astronomer-cosmos/actions/runs/12010604066/job/33477828079

**Comment by pankajastro** [comment]
Some discussion about this error
- https://github.com/dbt-labs/dbt-core/issues/10135
- https://github.com/PicnicSupermarket/dbt-score/issues/49
- https://github.com/dbt-labs/dbt-core/issues/9334

This weird that why it complaining `ModuleNotFoundError: No module named 'dbt.adapters.factory'` given that dbt-adapters already is here is dependency: https://github.com/dbt-labs/dbt-postgres/blob/352244812ec913ea342c1c86d7161fdb75f1e9b4/pyproject.toml#L25-L33 based on suggestion: https://github.com/dbt-labs/dbt-core/issues/10135#issuecomment-2116226848 I have created a PR: https://github.com/astronomer/astronomer-cosmos/pull/1364
