### ISSUE TITLE
[Bug] "'ProjectConfig' object has no attribute 'project_name'" when using ExecutionMode.KUBERNETES

### ISSUE THREAD

**Issue by col** [astronomer/astronomer-cosmos#1369]
### Astronomer Cosmos Version

1.7.1

### dbt-core version

1.7.19

### Versions of dbt adapters

dbt-postgres~=1.7.19

### LoadMode

AUTOMATIC

### ExecutionMode

KUBERNETES

### InvocationMode

DBT_RUNNER

### airflow version

2.10.3

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### What happened?

I'm trying to setup by first Dbt DAG. 

```
import os

from airflow import DAG
from airflow.providers.cncf.kubernetes.secret import Secret
from pendulum import datetime

from cosmos import (
    DbtTaskGroup,
    ExecutionConfig,
    ExecutionMode,
    ProfileConfig,
    ProjectConfig,
    RenderConfig,
)
from cosmos.profiles import PostgresUserPasswordProfileMapping

PROJECT_DIR = "/opt/airflow/dags/repo/dbt/my_project"
K8S_PROJECT_DIR="/dbt/my_project"
DBT_IMAGE = "my_project-dbt:latest"

postgres_password_secret = Secret(
    deploy_type="env",
    deploy_target="POSTGRES_PASSWORD",
    secret="my_project-secret",
    key="password",
)

postgres_host_secret = Secret(
    deploy_type="env",
    deploy_target="POSTGRES_HOST",
    secret="my_project-secret",
    key="host",
)

with DAG(
    dag_id="dbt_dag",
    start_date=datetime(2024, 12, 6),
    doc_md=__doc__,
    catchup=False,
) as dag:

    run_models = DbtTaskGroup(
        project_config=ProjectConfig(),
        render_config=RenderConfig(dbt_project_path=PROJECT_DIR),
        profile_config=ProfileConfig(
            profile_name="k8s_profile",
            target_name="warehouse",
            profile_mapping=PostgresUserPasswordProfileMapping(
                conn_id="dev-warehouse",
                profile_args={
                    "schema": "public",
                },
            ),
        ),
        execution_config=ExecutionConfig(execution_mode=ExecutionMode.KUBERNETES, dbt_project_path=K8S_PROJECT_DIR),
        operator_args={
            "image": DBT_IMAGE,
            "image_pull_policy": "Always",
            "image_pull_secrets": "my-registry-secret",
            "get_logs": True,
            "is_delete_operator_pod": False,
            "secrets": [postgres_password_secret, postgres_host_secret],
        },
    )

    run_models
```

When Airflow parses this DAG I get the following error:

```
Broken DAG: [/opt/airflow/dags/repo/dags/dbt_dag.py]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 301, in __init__
    dbt_project_name=project_config.project_name,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProjectConfig' object has no attribute 'project_name'
```

I have tried many variations of this:

1. Set the dbt_project_path in the ProjectConfig instead of in RenderConfig and ExecutionConfig. 
This will load the DAG correctly but will fail at runtime as the project path used on the k8s pod running the DAG is incorrect.

2. Set the project_name in the ProjectConfig and the appropriate dbt_project_path in RenderConfig and ExecutionConfig
Airflow fails to parse the DAG with the following error:
```
Broken DAG: [/opt/airflow/dags/repo/dags/dbt_dag.py]
Traceback (most recent call last):
  File "/opt/airflow/dags/repo/dags/dbt_dag.py", line 50, in <module>
    project_config=ProjectConfig(project_name="jiva_platform"),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 172, in __init__
    raise CosmosValueError(
cosmos.exceptions.CosmosValueError: If ProjectConfig.dbt_project_path is not defined, ProjectConfig.manifest_path and ProjectConfig.project_name must be defined together, or both left undefined.
```
However, I don't want to use 'Cosmos’ manifest parsing mode'

3. Trying to set the dbt_project_path on all three: ProjectConfig, RenderConfig and ExecutionConfig
Airflow fails to parse the DAG with the following error:
```
Broken DAG: [/opt/airflow/dags/repo/dags/dbt_dag.py]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 219, in __init__
    validate_initial_user_config(execution_config, profile_config, project_config, render_config, operator_args)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/converter.py", line 128, in validate_initial_user_config
    raise CosmosValueError(
cosmos.exceptions.CosmosValueError: ProjectConfig.dbt_project_path is mutually exclusive with RenderConfig.dbt_project_path and ExecutionConfig.dbt_project_path.If using RenderConfig.dbt_project_path or ExecutionConfig.dbt_project_path, ProjectConfig.dbt_project_path should be None
```

At this point I'm not sure how this is supposed to work. The path to the dbt project is different between Airflow and the image used to run DBT but cosmos is not letting me configure it correctly. What am I missing??

### Relevant log output

```shell

```

### How to reproduce

Using the DAG definition provided above should be enough to re-create this issue

### Anything else :)?

Everyt time

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Contact Details

colin@jiva.ag

**Comment by col** [comment]
While looking into patching this myself I realised it was already fixed by #1307 and released in 1.8.0a2.

I've updated to this release and it's now working as expected!

**Comment by tatiana** [comment]
Thanks for the feedback, @col. We aim to release Cosmos 1.8.0 on 20 December. We're glad it solved the issue. I'm closing this bug for now.
