### ISSUE TITLE
[Databricks] Running a Notebook task without WorkflowTaskGroup fails

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-cosmos#160]
The following DAG for DatabricksNotebookOperator without DatabricksWorkflowTaskGroup fails.
```
dag = DAG(
    dag_id="example_databricks_notebook",
    start_date=datetime(2022, 1, 1),
    schedule_interval=None,
    catchup=False,
    default_args=default_args,
)
with dag:
    # [START howto_databricks_workflow_notebook]
    notebook_1 = DatabricksNotebookOperator(
        task_id="notebook_1",
        databricks_conn_id=DATABRICKS_CONN_ID,
        notebook_path="notebook-path",
        notebook_packages=[
            {
                "pypi": {
                    "package": "Faker"
                }
            }
        ],
        source="WORKSPACE",
        job_cluster_key="random_cluster_key",
        existing_cluster_id="existing-cluster-id"
    )
```

The error is as below:
```
[2023-02-23, 16:24:19 UTC] {base.py:73} INFO - Using connection ID 'databricks_conn' for task execution.
[2023-02-23, 16:24:21 UTC] {base.py:73} INFO - Using connection ID 'databricks_conn' for task execution.
[2023-02-23, 16:24:22 UTC] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/databricks/notebook.py", line 229, in execute
    self.monitor_databricks_job()
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/databricks/notebook.py", line 139, in monitor_databricks_job
    current_task = self._get_current_databricks_task(runs_api)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/databricks/notebook.py", line 148, in _get_current_databricks_task
    x["task_key"]: x for x in runs_api.get_run(self.databricks_run_id)["tasks"]
KeyError: 'tasks'
[2023-02-23, 16:24:22 UTC] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=example_databricks_notebook, task_id=notebook_1, execution_date=20230223T162205, start_date=20230223T162418, end_date=20230223T162422
[2023-02-23, 16:24:22 UTC] {manager.py:61} WARNING - Unable to find an extractor. task_type=DatabricksNotebookOperator airflow_dag_id=example_databricks_notebook task_id=notebook_1 airflow_run_id=manual__2023-02-23T16:22:05.952374+00:00 
[2023-02-23, 16:24:22 UTC] {console.py:22} INFO - {"eventTime": "2023-02-23T16:24:22.869254Z", "eventType": "FAIL", "inputs": [], "job": {"facets": {}, "name": "example_databricks_notebook.notebook_1", "namespace": "default"}, "outputs": [], "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.18.0/integration/airflow", "run": {"facets": {"unknownSourceAttribute": {"_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.18.0/integration/airflow", "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/BaseFacet", "unknownItems": [{"name": "DatabricksNotebookOperator", "properties": {"_BaseOperator__from_mapped": false, "_BaseOperator__init_kwargs": {"databricks_conn_id": "databricks_conn", "execution_timeout": "<<non-serializable: timedelta>>", "existing_cluster_id": "1028-033729-pgbj7n9x", "job_cluster_key": "random_cluster_key", "notebook_packages": [{"pypi": {"package": "Faker"}}], "notebook_path": "/Users/pankaj.koti@astronomer.io/Notebook1", "retries": 2, "retry_delay": "<<non-serializable: timedelta>>", "source": "WORKSPACE", "task_id": "notebook_1"}, "_BaseOperator__instantiated": true, "_dag": "<<non-serializable: DAG>>", "_log": "<<non-serializable: Logger>>", "databricks_conn_id": "databricks_conn", "databricks_run_id": "", "depends_on_past": false, "do_xcom_push": true, "downstream_task_ids": [], "email_on_failure": true, "email_on_retry": true, "execution_timeout": "<<non-serializable: timedelta>>", "executor_config": {}, "existing_cluster_id": "1028-033729-pgbj7n9x", "ignore_first_depends_on_past": true, "inlets": [], "job_cluster_key": "random_cluster_key", "new_cluster": {}, "notebook_packages": [{"pypi": {"package": "Faker"}}], "notebook_params": {}, "notebook_path": "/Users/pankaj.koti@astronomer.io/Notebook1", "outlets": [], "owner": "airflow", "params": "<<non-serializable: ParamsDict>>", "pool": "default_pool", "pool_slots": 1, "priority_weight": 1, "queue": "default", "retries": 2, "retry_delay": "<<non-serializable: timedelta>>", "retry_exponential_backoff": false, "source": "WORKSPACE", "start_date": "<<non-serializable: DateTime>>", "task_group": "<<non-serializable: TaskGroup>>", "task_id": "notebook_1", "trigger_rule": "all_success", "upstream_task_ids": [], "wait_for_downstream": false, "weight_rule": "downstream"}, "type": "operator"}]}}, "runId": "0d74df72-5650-4b1e-95ba-442729cbee1f"}}
[2023-02-23, 16:24:22 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 103 for task notebook_1 ('tasks'; 14808)
[2023-02-23, 16:24:22 UTC] {local_task_job.py:159} INFO - Task exited with return code 1
```

**Comment by jlaneve** [comment]
Good catch - we should explicitly check to make sure it's within the WorkflowTaskGroup, and if it's not, raise a more specific error.

**Comment by tatiana** [comment]
@jlaneve isn't this a valid use-case (instantiate Notebooks outside of a Task Group)? Perhaps we should fix the code so we support this use case, as opposed to improving the error message, WDYT?

**Comment by pankajkoti** [comment]
The latest Databricks Jobs API 2.1 https://docs.databricks.com/dev-tools/api/latest/jobs.html offers a consistent response for both a single task and multi-task job run submit API. We're leveraging that to fix this issue and I have created a PR https://docs.databricks.com/dev-tools/api/latest/jobs.html for the same. Also, tested an example DAG to test the same which has been added to the PR.
