### ISSUE TITLE
Airflow dbt adapter - Error getting profile "bigquery_profile" running on GCP Composer

### ISSUE THREAD

**Issue by vmasilva** [astronomer/astronomer-cosmos#181]
Hi,

I am trying to use the DbtTaskGroup in Airflow. 
I am using GCP Cloud Composer version: composer-2.1.8-airflow-2.4.3 
I was able to installed the package via pypi directly, without need venv.

The DAG model generation is ok - great - I was able to see my DBT tasks in airflow DAG.
However I am not able to run dbt - I get an error related with the profile. 

Following this guide: https://astronomer.github.io/astronomer-cosmos/dbt/connections.html what I have done was:
1 - Create an Airflow connection named "bigquery_default", introducing the service account.
2 - In the DAG File I specified conn_id="bigquery_default",
3 - When I run it, I get the following error: 
"[2023-03-08, 17:42:25 UTC] {subprocess.py:75} INFO - Running command: ['dbt', 'run', '--project-dir', '/home/airflow/gcs/dags/dbt/jaffle_shop', '--models', 'my_first_dbt_model', '--profile', 'bigquery_profile']
[2023-03-08, 17:42:25 UTC] {subprocess.py:86} INFO - Output:
[2023-03-08, 17:42:33 UTC] {subprocess.py:93} INFO - 17:42:33  Encountered an error while reading the project:  ERROR: Runtime Error
[2023-03-08, 17:42:33 UTC] {subprocess.py:93} INFO -   Could not find profile named **'bigquery_profile'**

From what I read, the profile should be created in memory, but it looks that dbt is not be able to found the profile. 
Could you provide some help? 

Find compelete log and source file below:

------------------------------------------------------------------------------------------------------------------------------------------
Complete Log:
```
*** Reading remote log from gs://europe-west1-composer-airfl-2764f717-bucket/logs/dag_id=extract_dag/run_id=manual__2023-03-08T17:19:48.841788+00:00/task_id=dbt_tg.my_first_dbt_model.my_first_dbt_model_run/attempt=1.log.
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1166} INFO - Dependencies all met for <TaskInstance: extract_dag.dbt_tg.my_first_dbt_model.my_first_dbt_model_run manual__2023-03-08T17:19:48.841788+00:00 [queued]>
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1166} INFO - Dependencies all met for <TaskInstance: extract_dag.dbt_tg.my_first_dbt_model.my_first_dbt_model_run manual__2023-03-08T17:19:48.841788+00:00 [queued]>
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1363} INFO - 
--------------------------------------------------------------------------------
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1364} INFO - Starting attempt 1 of 3
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1365} INFO - 
--------------------------------------------------------------------------------
[2023-03-08, 17:19:52 UTC] {taskinstance.py:1384} INFO - Executing <Task(DbtRunOperator): dbt_tg.my_first_dbt_model.my_first_dbt_model_run> on 2023-03-08 17:19:48.841788+00:00
[2023-03-08, 17:19:52 UTC] {standard_task_runner.py:55} INFO - Started process 31237 to run task
[2023-03-08, 17:19:52 UTC] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'dbt_tg.my_first_dbt_model.my_first_dbt_model_run', 'manual__2023-03-08T17:19:48.841788+00:00', '--job-id', '550', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmp9rn_00fg']
[2023-03-08, 17:19:52 UTC] {standard_task_runner.py:83} INFO - Job 550: Subtask dbt_tg.my_first_dbt_model.my_first_dbt_model_run
[2023-03-08, 17:19:52 UTC] {task_command.py:381} INFO - Running <TaskInstance: extract_dag.dbt_tg.my_first_dbt_model.my_first_dbt_model_run manual__2023-03-08T17:19:48.841788+00:00 [running]> on host airflow-worker-txhrm
[2023-03-08, 17:19:53 UTC] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=dbt_tg.my_first_dbt_model.my_first_dbt_model_run
AIRFLOW_CTX_EXECUTION_DATE=2023-03-08T17:19:48.841788+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-08T17:19:48.841788+00:00
[2023-03-08, 17:19:53 UTC] {base.py:71} INFO - Using connection ID 'bigquery_default' for task execution.
[2023-03-08, 17:19:53 UTC] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-08, 17:19:53 UTC] {subprocess.py:75} INFO - Running command: ['dbt', 'run', '--project-dir', '/home/airflow/gcs/dags/dbt/jaffle_shop', '--models', 'my_first_dbt_model', '--profile', 'bigquery_profile']
[2023-03-08, 17:19:53 UTC] {subprocess.py:86} INFO - Output:
[2023-03-08, 17:20:00 UTC] {subprocess.py:93} INFO - 17:20:00  Encountered an error while reading the project:  ERROR: Runtime Error
[2023-03-08, 17:20:00 UTC] {subprocess.py:93} INFO -   Could not find profile named 'bigquery_profile'
[2023-03-08, 17:20:00 UTC] {subprocess.py:93} INFO - 17:20:00  Encountered an error:
[2023-03-08, 17:20:00 UTC] {subprocess.py:93} INFO - Runtime Error
[2023-03-08, 17:20:00 UTC] {subprocess.py:93} INFO -   Could not run dbt
[2023-03-08, 17:20:01 UTC] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-08, 17:20:01 UTC] {taskinstance.py:1853} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators.py", line 341, in execute
    result = self.build_and_run_cmd(env=self.get_env(context))
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators.py", line 262, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env)
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators.py", line 226, in run_command
    self.exception_handling(result)
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators.py", line 164, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 2.
[2023-03-08, 17:20:01 UTC] {taskinstance.py:1402} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=dbt_tg.my_first_dbt_model.my_first_dbt_model_run, execution_date=20230308T171948, start_date=20230308T171952, end_date=20230308T172001
[2023-03-08, 17:20:01 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 550 for task dbt_tg.my_first_dbt_model.my_first_dbt_model_run (dbt command failed. The command returned a non-zero exit code 2.; 31237)
[2023-03-08, 17:20:02 UTC] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-08, 17:20:02 UTC] {taskinstance.py:2626} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

My Dag source file - extract_dag.py

```
from pendulum import datetime

from airflow import DAG
from airflow.operators.empty import EmptyOperator
from cosmos.providers.dbt.task_group import DbtTaskGroup


with DAG(
    dag_id="extract_dag",
    start_date=datetime(2022, 11, 27),
    schedule="@daily",
) as dag:

    e1 = EmptyOperator(task_id="ingestion_workflow")

    dbt_tg = DbtTaskGroup(
        group_id="dbt_tg",
        dbt_root_path="/home/airflow/gcs/dags/dbt",
        dbt_models_dir="/home/airflow/gcs/dags/dbt/jaffle_shop/models",
        dbt_project_name="jaffle_shop",
        #conn_id="airflow_db",
        conn_id="bigquery_default",
        dbt_args={
            "db_name": "bi4all-elt-framework-dev",
            "schema": "test_dbt_composer"
        },
    )

    e2 = EmptyOperator(task_id="some_extraction")

    e1 >> dbt_tg >> e2

```
---------------------------------------------------------------------
---------------------------------------------------------------------

**Comment by pohek321** [comment]
@vmasilva how are you creating the connection to your BigQuery? Do you have a connection in Airflow that's doing that? We currently only support putting a service account's JSON creds in the Airflow connection. For more information on setting up a bigquery connection that Cosmos can use, please see the connection docs [here](https://astronomer.github.io/astronomer-cosmos/dbt/connections.html)

**Comment by jackwelty** [comment]
I can second this, I'm using (nearly) the same code from the example, created a Google Cloud Platform connection in Airflow with my service account json and am getting the same error, both locally and deployed to Astro.

**Comment by jlaneve** [comment]
Is this with a service account JSON or service account JSON file? We do support the file, but we don't support the raw JSON yet. If you'd like to contribute, this should be pretty straightforward! https://astronomer.github.io/astronomer-cosmos/dbt/connections-profiles.html#connections-and-profiles
