### ISSUE TITLE
Installation of package on astro-runtime fails

### ISSUE THREAD

**Issue by ecjumbe** [astronomer/astronomer-cosmos#184]
I am currently attempting to install this package in the **astro-runtime:7.3.0** image using **Astro CLI Version: 1.11.0**. After running the command `astro dev start` the building of the image is failing due to numpy failing to install. A section of the error is as folows:

```
error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [640 lines of output]
      Looking in indexes: https://pip.astronomer.io/v2/
      Looking in links: https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-airflow-version-check/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-airflow-version-check/
      Collecting setuptools>=40.6.0
        Downloading setuptools-67.6.0-py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.0 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting cython
        Downloading Cython-0.29.33-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 43.2 MB/s eta 0:00:00
      Collecting pyarrow<0.18.0,>=0.17.0
        Downloading pyarrow-0.17.1.tar.gz (2.6 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 35.4 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [607 lines of output]
            Looking in indexes: https://pip.astronomer.io/v2/
            Looking in links: https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-airflow-version-check/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-airflow-version-check/, https://pip.astronomer.io/simple/astronomer-fab-security-manager/, https://pip.astronomer.io/simple/astronomer-airflow-version-check/
            Ignoring numpy: markers 'python_version < "3.7"' don't match your environment
            Collecting cython>=0.29
              Downloading Cython-0.29.33-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 24.7 MB/s eta 0:00:00
            Collecting numpy==1.16.0
              Downloading numpy-1.16.0.zip (5.1 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 43.5 MB/s eta 0:00:00
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting setuptools
              Downloading setuptools-67.6.0-py3-none-any.whl (1.1 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 41.3 MB/s eta 0:00:00
            Collecting setuptools_scm
              Downloading setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 122.4 MB/s eta 0:00:00
            Collecting wheel
              Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
            Collecting tomli>=1.0.0
              Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
            Collecting typing-extensions
              Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
            Collecting packaging>=20.0
              Downloading packaging-23.0-py3-none-any.whl (42 kB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 241.0 MB/s eta 0:00:00
            Building wheels for collected packages: numpy
              Building wheel for numpy (setup.py): started
              Building wheel for numpy (setup.py): finished with status 'error'
              error: subprocess-exited-with-error
      
              × python setup.py bdist_wheel did not run successfully.
              │ exit code: 1
              ╰─> [260 lines of output]
                  Running from numpy source directory.
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/misc_util.py:476: SyntaxWarning: "is" with a literal. Did you mean "=="?
                    return is_string(s) and ('*' in s or '?' is s)
                  blas_opt_info:
                  blas_mkl_info:
                  customize UnixCCompiler
                    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  blis_info:
                  customize UnixCCompiler
                    libraries blis not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_blas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_blas_info:
                  customize UnixCCompiler
                    libraries satlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_blas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_blas_info:
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  accelerate_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [atlas]) or by setting
                      the ATLAS environment variable.
                    self.calc_info()
                  blas_info:
                  customize UnixCCompiler
                    libraries blas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Blas (http://www.netlib.org/blas/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [blas]) or by setting
                      the BLAS environment variable.
                    self.calc_info()
                  blas_src_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Blas (http://www.netlib.org/blas/) sources not found.
                      Directories to search for the sources can be specified in the
                      numpy/distutils/site.cfg file (section [blas_src]) or by setting
                      the BLAS_SRC environment variable.
                    self.calc_info()
                    NOT AVAILABLE
      
                  /bin/sh: 1: svnversion: not found
                  non-existing path in 'numpy/distutils': 'site.cfg'
                  lapack_opt_info:
                  lapack_mkl_info:
                  customize UnixCCompiler
                    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_lapack_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_clapack_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries tatlas,tatlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries tatlas,tatlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
                    NOT AVAILABLE
      
                  atlas_3_10_info:
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries satlas,satlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries satlas,satlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_3_10_info'>
                    NOT AVAILABLE
      
                  atlas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_threads_info'>
                    NOT AVAILABLE
      
                  atlas_info:
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_info'>
                    NOT AVAILABLE
      
                  lapack_info:
                  customize UnixCCompiler
                    libraries lapack not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Lapack (http://www.netlib.org/lapack/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [lapack]) or by setting
                      the LAPACK environment variable.
                    self.calc_info()
                  lapack_src_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Lapack (http://www.netlib.org/lapack/) sources not found.
                      Directories to search for the sources can be specified in the
                      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                      the LAPACK_SRC environment variable.
                    self.calc_info()
                    NOT AVAILABLE
      
                  /usr/local/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
                    warnings.warn(msg)
                  running bdist_wheel
                  running build
                  running config_cc
                  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
                  running config_fc
                  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
                  running build_src
                  build_src
                  building py_modules sources
                  creating build
                  creating build/src.linux-x86_64-3.9
                  creating build/src.linux-x86_64-3.9/numpy
                  creating build/src.linux-x86_64-3.9/numpy/distutils
                  building library "npymath" sources
                  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
                  customize Gnu95FCompiler
                  Could not locate executable gfortran
                  Could not locate executable f95
                  customize IntelFCompiler
                  Could not locate executable ifort
                  Could not locate executable ifc
                  customize LaheyFCompiler
                  Could not locate executable lf95
                  customize PGroupFCompiler
                  Could not locate executable pgfortran
                  customize AbsoftFCompiler
                  Could not locate executable f90
                  Could not locate executable f77
                  customize NAGFCompiler
                  customize VastFCompiler
                  customize CompaqFCompiler
                  Could not locate executable fort
                  customize IntelItaniumFCompiler
                  Could not locate executable efort
                  Could not locate executable efc
                  customize IntelEM64TFCompiler
                  customize GnuFCompiler
                  Could not locate executable g77
                  customize G95FCompiler
                  Could not locate executable g95
                  customize PathScaleFCompiler
                  Could not locate executable pathf95
                  customize NAGFORCompiler
                  Could not locate executable nagfor
                  don't know how to compile Fortran code on platform 'posix'
                  C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
                  compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.9 -c'
                  gcc: _configtest.c
                  failure.
                  removing: _configtest.c _configtest.o
                  Traceback (most recent call last):
                    File "<string>", line 2, in <module>
                    File "<pip-setuptools-caller>", line 34, in <module>
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/setup.py", line 415, in <module>
                      setup_package()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/setup.py", line 407, in setup_package
                      setup(**metadata)
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/core.py", line 171, in setup
                      return old_setup(**new_attr)
                    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
                      return distutils.core.setup(**attrs)
                    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
                      dist.run_commands()
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
                      self.run_command(cmd)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 325, in run
                      self.run_command("build")
                    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
                      self.distribution.run_command(command)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build.py", line 47, in run
                      old_build.run(self)
                    File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
                      self.run_command(cmd_name)
                    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
                      self.distribution.run_command(command)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 148, in run
                      self.build_sources()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 159, in build_sources
                      self.build_library_sources(*libname_info)
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 292, in build_library_sources
                      sources = self.generate_sources(sources, (lib_name, build_info))
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 375, in generate_sources
                      source = func(extension, build_dir)
                    File "numpy/core/setup.py", line 667, in get_mathlib_info
                      raise RuntimeError("Broken toolchain: cannot link a simple C program")
                  RuntimeError: Broken toolchain: cannot link a simple C program
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed building wheel for numpy
              Running setup.py clean for numpy
              error: subprocess-exited-with-error
      
              × python setup.py clean did not run successfully.
              │ exit code: 1
              ╰─> [10 lines of output]
                  Running from numpy source directory.
      
                  `setup.py clean` is not supported, use one of the following instead:
      
                    - `git clean -xdf` (cleans all files)
                    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                        files that aren't checked into the git repo)
      
                  Add `--force` to your command to use it anyway if you must (unsupported).
      
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
              ERROR: Failed cleaning build dir for numpy
            Failed to build numpy
            Installing collected packages: wheel, typing-extensions, tomli, setuptools, packaging, numpy, cython, setuptools_scm
              Running setup.py install for numpy: started
              Running setup.py install for numpy: finished with status 'error'
              error: subprocess-exited-with-error
      
              × Running setup.py install for numpy did not run successfully.
              │ exit code: 1
              ╰─> [267 lines of output]
                  Running from numpy source directory.
      
                  Note: if you need reliable uninstall behavior, then install
                  with pip instead of using `setup.py install`:
      
                    - `pip install .`       (from a git repo or downloaded source
                                             release)
                    - `pip install numpy`   (last NumPy release on PyPi)
      
      
                  blas_opt_info:
                  blas_mkl_info:
                  customize UnixCCompiler
                    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  blis_info:
                  customize UnixCCompiler
                    libraries blis not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_blas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_blas_info:
                  customize UnixCCompiler
                    libraries satlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_blas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_blas_info:
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  accelerate_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [atlas]) or by setting
                      the ATLAS environment variable.
                    self.calc_info()
                  blas_info:
                  customize UnixCCompiler
                    libraries blas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Blas (http://www.netlib.org/blas/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [blas]) or by setting
                      the BLAS environment variable.
                    self.calc_info()
                  blas_src_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Blas (http://www.netlib.org/blas/) sources not found.
                      Directories to search for the sources can be specified in the
                      numpy/distutils/site.cfg file (section [blas_src]) or by setting
                      the BLAS_SRC environment variable.
                    self.calc_info()
                    NOT AVAILABLE
      
                  /bin/sh: 1: svnversion: not found
                  non-existing path in 'numpy/distutils': 'site.cfg'
                  lapack_opt_info:
                  lapack_mkl_info:
                  customize UnixCCompiler
                    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_lapack_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  openblas_clapack_info:
                  customize UnixCCompiler
                  customize UnixCCompiler
                    libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  atlas_3_10_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries tatlas,tatlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries tatlas,tatlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
                    NOT AVAILABLE
      
                  atlas_3_10_info:
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries satlas,satlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries satlas,satlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_3_10_info'>
                    NOT AVAILABLE
      
                  atlas_threads_info:
                  Setting PTATLAS=ATLAS
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_threads_info'>
                    NOT AVAILABLE
      
                  atlas_info:
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in /usr/local/lib
                  customize UnixCCompiler
                    libraries lapack_atlas not found in /usr/lib
                  customize UnixCCompiler
                    libraries f77blas,cblas,atlas not found in /usr/lib
                  <class 'numpy.distutils.system_info.atlas_info'>
                    NOT AVAILABLE
      
                  lapack_info:
                  customize UnixCCompiler
                    libraries lapack not found in ['/usr/local/lib', '/usr/lib']
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Lapack (http://www.netlib.org/lapack/) libraries not found.
                      Directories to search for the libraries can be specified in the
                      numpy/distutils/site.cfg file (section [lapack]) or by setting
                      the LAPACK environment variable.
                    self.calc_info()
                  lapack_src_info:
                    NOT AVAILABLE
      
                  /tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/system_info.py:625: UserWarning:
                      Lapack (http://www.netlib.org/lapack/) sources not found.
                      Directories to search for the sources can be specified in the
                      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                      the LAPACK_SRC environment variable.
                    self.calc_info()
                    NOT AVAILABLE
      
                  /usr/local/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
                    warnings.warn(msg)
                  running install
                  running build
                  running config_cc
                  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
                  running config_fc
                  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
                  running build_src
                  build_src
                  building py_modules sources
                  building library "npymath" sources
                  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
                  customize Gnu95FCompiler
                  Could not locate executable gfortran
                  Could not locate executable f95
                  customize IntelFCompiler
                  Could not locate executable ifort
                  Could not locate executable ifc
                  customize LaheyFCompiler
                  Could not locate executable lf95
                  customize PGroupFCompiler
                  Could not locate executable pgfortran
                  customize AbsoftFCompiler
                  Could not locate executable f90
                  Could not locate executable f77
                  customize NAGFCompiler
                  customize VastFCompiler
                  customize CompaqFCompiler
                  Could not locate executable fort
                  customize IntelItaniumFCompiler
                  Could not locate executable efort
                  Could not locate executable efc
                  customize IntelEM64TFCompiler
                  customize GnuFCompiler
                  Could not locate executable g77
                  customize G95FCompiler
                  Could not locate executable g95
                  customize PathScaleFCompiler
                  Could not locate executable pathf95
                  customize NAGFORCompiler
                  Could not locate executable nagfor
                  don't know how to compile Fortran code on platform 'posix'
                  C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
      
                  compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.9 -c'
                  gcc: _configtest.c
                  failure.
                  removing: _configtest.c _configtest.o
                  Traceback (most recent call last):
                    File "<string>", line 2, in <module>
                    File "<pip-setuptools-caller>", line 34, in <module>
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/setup.py", line 415, in <module>
                      setup_package()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/setup.py", line 407, in setup_package
                      setup(**metadata)
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/core.py", line 171, in setup
                      return old_setup(**new_attr)
                    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
                      return distutils.core.setup(**attrs)
                    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
                      dist.run_commands()
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
                      self.run_command(cmd)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/install.py", line 62, in run
                      r = self.setuptools_run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/install.py", line 36, in setuptools_run
                      return distutils_install.run(self)
                    File "/usr/local/lib/python3.9/distutils/command/install.py", line 546, in run
                      self.run_command('build')
                    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
                      self.distribution.run_command(command)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build.py", line 47, in run
                      old_build.run(self)
                    File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
                      self.run_command(cmd_name)
                    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
                      self.distribution.run_command(command)
                    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
                      cmd_obj.run()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 148, in run
                      self.build_sources()
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 159, in build_sources
                      self.build_library_sources(*libname_info)
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 292, in build_library_sources
                      sources = self.generate_sources(sources, (lib_name, build_info))
                    File "/tmp/pip-install-8yqmrt4h/numpy_a96755816d6047c694f99e892991b029/numpy/distutils/command/build_src.py", line 375, in generate_sources
                      source = func(extension, build_dir)
                    File "numpy/core/setup.py", line 667, in get_mathlib_info
                      raise RuntimeError("Broken toolchain: cannot link a simple C program")
                  RuntimeError: Broken toolchain: cannot link a simple C program
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: legacy-install-failure
      
            × Encountered error while trying to install package.
            ╰─> numpy
      
            note: This is an issue with the package mentioned above, not pip.
            hint: See above for output from the failure.
      
            [notice] A new release of pip available: 22.3.1 -> 23.0.1
            [notice] To update, run: pip install --upgrade pip
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      
      [notice] A new release of pip available: 22.3.1 -> 23.0.1
      [notice] To update, run: pip install --upgrade pip
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
The command '/bin/bash -o pipefail -e -u -x -c if grep -Eqx 'apache-airflow\s*[=~>]{1,2}.*' requirements.txt; then     echo >&2 "Do not upgrade by specifying 'apache-airflow' in your requirements.txt, change the base image instead!";  exit 1;   fi;   pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
Error: command 'docker build -t astro-airflow_8b91e8/airflow:latest failed: failed to execute cmd: exit status 1
```

**Comment by pohek321** [comment]
@ecjumbe would you mind replying with the contents of your `requirements.txt` and `Dockerfile`? Hard to know why the build is failing without seeing the contents of those.

**Comment by ecjumbe** [comment]
This is the content of the requirements file:
```
apache-airflow-providers-databricks==2.5.0
astronomer-cosmos[dbt-all]
```
