### ISSUE TITLE
Possible race condition with multiple DbtTaskGroups starting at the same time.

### ISSUE THREAD

**Issue by mpgreg** [astronomer/astronomer-cosmos#226]
With task_group nesting if I create a TG of DbtTaskGroups I get random errors on some tasks and clearing the task or the whole taskgroup seems to work every time.

```[2023-04-06, 17:55:37 UTC] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-04-06, 17:55:37 UTC] {operators.py:247} INFO - Changes detected - copying /usr/local/airflow/include/dbt/jaffle_shop to /tmp/dbt/jaffle_shop
[2023-04-06, 17:55:37 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 387, in execute
    result = self.build_and_run_cmd(context=context)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 312, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 276, in run_command
    shutil.copytree(self.project_dir, target_dir, ignore=exclude)
  File "/usr/local/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/lib/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [('/usr/local/airflow/include/dbt/jaffle_shop/macros/drop_table.sql', '/tmp/dbt/jaffle_shop/macros/drop_table.sql', "[Errno 2] No such file or directory: '/tmp/dbt/jaffle_shop/macros/drop_table.sql'"), ('/usr/local/airflow/include/dbt/jaffle_shop/macros/generate_schema_name.sql', '/tmp/dbt/jaffle_shop/macros/generate_schema_name.sql', "[Errno 2] No such file or directory: '/tmp/dbt/jaffle_shop/macros/generate_schema_name.sql'")]
[2023-04-06, 17:55:37 UTC] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=customer_analytics, task_id=transform.jaffle_shop.customers_run, execution_date=20230406T175520, start_date=20230406T175537, end_date=20230406T175537
[2023-04-06, 17:55:37 UTC] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task transform.jaffle_shop.customers_run ([('/usr/local/airflow/include/dbt/jaffle_shop/macros/drop_table.sql', '/tmp/dbt/jaffle_shop/macros/drop_table.sql', "[Errno 2] No such file or directory: '/tmp/dbt/jaffle_shop/macros/drop_table.sql'"), ('/usr/local/airflow/include/dbt/jaffle_shop/macros/generate_schema_name.sql', '/tmp/dbt/jaffle_shop/macros/generate_schema_name.sql', "[Errno 2] No such file or directory: '/tmp/dbt/jaffle_shop/macros/generate_schema_name.sql'")]; 402)
[2023-04-06, 17:55:37 UTC] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-06, 17:55:37 UTC] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check```

**Comment by mpgreg** [comment]
Logging into the scheduler I can see that the directories and files in /tmp do exist. 

My DAG code looks like:
```
@task_group()
    def transform(loaded_data:dict):

        jaffle_shop = DbtTaskGroup(
            dbt_project_name="jaffle_shop",
            dbt_root_path="/usr/local/airflow/include/dbt",
            conn_id=_SNOWFLAKE_CONN,
            dbt_args={"dbt_executable_path": _DBT_BIN},
            test_behavior="after_all",
        )
        
        attribution_playbook = DbtTaskGroup(
            dbt_project_name="attribution_playbook",
            dbt_root_path="/usr/local/airflow/include/dbt",
            conn_id=_SNOWFLAKE_CONN,
            dbt_args={"dbt_executable_path": _DBT_BIN},
        )

        mrr_playbook = DbtTaskGroup(
            dbt_project_name="mrr_playbook",
            dbt_root_path="/usr/local/airflow/include/dbt",
            conn_id=_SNOWFLAKE_CONN,
            dbt_args={"dbt_executable_path": _DBT_BIN},
        )```

**Comment by mpgreg** [comment]
The above occurs with astronomer-cosmos==0.5.2.

Tested with astronomer-cosmos==0.5.1 and the failure does not occur.  

Possibly due to https://github.com/astronomer/astronomer-cosmos/pull/214/commits/204b14aa53d6cc32da04c151fc8bca25d9fbf7ae
