### ISSUE TITLE
pass --indirect-selection flag to specific task

### ISSUE THREAD

**Issue by nmema** [astronomer/astronomer-cosmos#261]
Hello,

 I have an example in this [repo](https://github.com/nmema/airflow-dbt-setup), where I'm trying to run two models: `stg_test` and `fct_test`. There is a [test](https://github.com/nmema/airflow-dbt-setup/blob/main/dbt/jaffle_shop/models/marts/schema.yml#L7-L9) in `fct_test`, where it checks the number of rows referencing `stg_test`. My problem comes when executing the [DAG](https://github.com/nmema/airflow-dbt-setup/blob/main/dags/test_dag.py): when the task `stg_test_test` executes, it should pass because it has no tests defined, but it runs a test that corresponds to `fct_test`. it will also fail because there is no data in the `fct_test` table yet:

log:
```
--------------------------------------------------------------------------------
[2023-04-28, 14:46:29 UTC] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-28, 14:46:29 UTC] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-28, 14:46:29 UTC] {taskinstance.py:1300} INFO - Executing <Task(DbtTestOperator): jaffle_shop.stg_test.stg_test_test> on 2023-04-28 14:46:10.105777+00:00
[2023-04-28, 14:46:29 UTC] {standard_task_runner.py:55} INFO - Started process 349 to run task
[2023-04-28, 14:46:29 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example', 'jaffle_shop.stg_test.stg_test_test', 'manual__2023-04-28T14:46:10.105777+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpfqfg6x8n']
[2023-04-28, 14:46:29 UTC] {standard_task_runner.py:83} INFO - Job 130: Subtask jaffle_shop.stg_test.stg_test_test
[2023-04-28, 14:46:30 UTC] {task_command.py:388} INFO - Running <TaskInstance: example.jaffle_shop.stg_test.stg_test_test manual__2023-04-28T14:46:10.105777+00:00 [running]> on host cdd723a0d4a1
[2023-04-28, 14:46:30 UTC] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example
AIRFLOW_CTX_TASK_ID=jaffle_shop.stg_test.stg_test_test
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T14:46:10.105777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T14:46:10.105777+00:00
[2023-04-28, 14:46:30 UTC] {base.py:73} INFO - Using connection ID 'bigquery_id' for task execution.
[2023-04-28, 14:46:30 UTC] {operators.py:279} INFO - No differences detected between /opt/***/dbt/jaffle_shop and /tmp/dbt/jaffle_shop
[2023-04-28, 14:46:30 UTC] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-28, 14:46:30 UTC] {subprocess.py:75} INFO - Running command: ['/home/***/.local/bin/dbt', 'test', '--project-dir', '/tmp/dbt/jaffle_shop', '--models', 'stg_test', '--profile', 'bigquery_profile']
[2023-04-28, 14:46:30 UTC] {subprocess.py:86} INFO - Output:
[2023-04-28, 14:46:36 UTC] {subprocess.py:93} INFO - [0m14:46:36  Running with dbt=1.4.5
[2023-04-28, 14:46:36 UTC] {subprocess.py:93} INFO - [0m14:46:36  Found 2 models, 1 test, 0 snapshots, 0 analyses, 338 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2023-04-28, 14:46:36 UTC] {subprocess.py:93} INFO - [0m14:46:36
[2023-04-28, 14:46:37 UTC] {subprocess.py:93} INFO - [0m14:46:37  Concurrency: 1 threads (target='dev')
[2023-04-28, 14:46:37 UTC] {subprocess.py:93} INFO - [0m14:46:37
[2023-04-28, 14:46:37 UTC] {subprocess.py:93} INFO - [0m14:46:37  1 of 1 START test count_fct_test_ref_stg_test_ ................................. [RUN]
[2023-04-28, 14:46:39 UTC] {subprocess.py:93} INFO - [0m14:46:39  1 of 1 FAIL 1 count_fct_test_ref_stg_test_ ..................................... [[31mFAIL 1[0m in 2.33s]
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40  Finished running 1 test in 0 hours 0 minutes and 3.31 seconds (3.31s).
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40  [31mCompleted with 1 error and 0 warnings:[0m
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40  [31mFailure in test count_fct_test_ref_stg_test_ (models/marts/schema.yml)[0m
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40    Got 1 result, configured to fail if != 0
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40    compiled Code at target/compiled/jaffle_shop/models/marts/schema.yml/count_fct_test_ref_stg_test_.sql
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40
[2023-04-28, 14:46:40 UTC] {subprocess.py:93} INFO - [0m14:46:40  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-04-28, 14:46:41 UTC] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-28, 14:46:41 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/providers/dbt/core/operators.py", line 403, in execute
    result = self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/providers/dbt/core/operators.py", line 312, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/providers/dbt/core/operators.py", line 288, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/providers/dbt/core/operators.py", line 193, in exception_handling
    f"dbt command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 1.
[2023-04-28, 14:46:41 UTC] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=example, task_id=jaffle_shop.stg_test.stg_test_test, execution_date=20230428T144610, start_date=20230428T144629, end_date=20230428T144641
[2023-04-28, 14:46:41 UTC] {standard_task_runner.py:105} ERROR - Failed to execute job 130 for task jaffle_shop.stg_test.stg_test_test (dbt command failed. The command returned a non-zero exit code 1.; 349)
[2023-04-28, 14:46:41 UTC] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-28, 14:46:41 UTC] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

As mention in the dbt docs: 
```As a general rule, dbt will indirectly select all tests if they touch any resource that you're selecting directly. We call this "eager" indirect selection.``` 

So I would like to pass the flag `--indirect-selection cautious` only to the `stg_test_test` task but I don't know which it could be the best approach. Any suggestions?

Thanks

**Comment by tatiana** [comment]
@nmema Sorry for the delay getting back to you on this.

Since Cosmos 1.2.1 you can specify the `--indirect-selection` flag, thanks to @david-mag :
https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.1
https://github.com/astronomer/astronomer-cosmos/pull/613/files
