### ISSUE TITLE
create_default_profiles error when trying to use a snowflake connection

### ISSUE THREAD

**Issue by wil-teampeanut** [astronomer/astronomer-cosmos#311]
I am trying to get astonomer-cosmos running on our DBT project sitting in a dags folder, running using MWW local composer.
The DBT project runs successfully using another package, but I like the view and layout provided by this package.
I have the following in my requirements.txt
```
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-slack==7.2.0
dbt-snowflake==1.4.2
airflow-dbt-python[snowflake,s3]==1.0.5
jsonschema==4.17.3
sqlglot==13.3.0
inflect==6.0.4
astronomer-cosmos[dbt-snowflake]
```

I am trying to use a Snowflake connection, I know it works as it is being used with airflow-dbt-python successfully. However I get the following error in all of the xxxx_run tasks:
```
[2023-06-06, 10:45:21 UTC] {{taskinstance.py:1768}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators/local.py", line 250, in execute
    result = self.build_and_run_cmd(context=context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators/local.py", line 157, in build_and_run_cmd
    dbt_cmd, env = self.build_cmd(context=context, cmd_flags=cmd_flags)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/operators/base.py", line 217, in build_cmd
    create_default_profiles(DBT_PROFILE_PATH)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/cosmos/providers/dbt/core/utils/profiles_generator.py", line 42, in create_default_profiles
    first_line = next(f)
StopIteration
```

**Comment by jlaneve** [comment]
This issue gets fixed with https://github.com/astronomer/astronomer-cosmos/pull/271. Should be merged and released today! I'll update this thread when there's a new version available.

**Comment by jlaneve** [comment]
version 0.7.0 is now out with this fix!

**Comment by wil-teampeanut** [comment]
Great, all working now
