### ISSUE TITLE
upgrading from 0.4.2 to 0.7.3 -> profile.yml cannot be created 

### ISSUE THREAD

**Issue by CorsettiS** [astronomer/astronomer-cosmos#343]
I recently upgraded my cosmos from 0.4.2 to 0.7.3 and DAGs that were perfectly working before are now throwing errors.

```
[2023-06-26, 17:10:03 UTC] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators/local.py", line 289, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=cmd_flags)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators/local.py", line 235, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/providers/dbt/core/operators/local.py", line 193, in run_command
    profile_mapping = get_profile_mapping(
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/providers/dbt/core/profiles/__init__.py", line 56, in get_profile_mapping
    raise ValueError(f"Could not find a profile mapping for connection {conn_id}.")
ValueError: Could not find a profile mapping for connection bigquery_default.
```

Here is the Dag Code

```
example_virtualenv = DbtDag(
    # dbt/cosmos-specific parameters
    dbt_root_path=f"{os.getenv('AIRFLOW_HOME')}/dbt/",
    dbt_project_name="jaffle_shop",
    conn_id="bigquery_default",
    dbt_args={"schema": "temp"},
    execution_mode="virtualenv",
    operator_args={
        "project_dir": f"{os.getenv('AIRFLOW_HOME')}/dbt/jaffle_shop",
        "py_system_site_packages": False,
        "py_requirements": ["dbt-bigquery==1.5.0"],
    },
    # normal dag parameters
    schedule_interval="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id="example_virtualenv",
)
```

I also tested for a local execution_mode and got the same error, which means that the project is likely broken somewhere during the profile.yml generation.

**Comment by jlaneve** [comment]
Interesting. What connection type is this?

**Comment by CorsettiS** [comment]
@jlaneve google_cloud_platform. I also tested the mysql connection with airflow db but got the same error. I am kinda clueless since I came back to contribute to the project after a long time but I cant set it up anymore :(

**Comment by jlaneve** [comment]
@CorsettiS do you see a log line that says something like:
```
Not using mapping GoogleCloudServiceAccountFileProfileMapping because XXX is not set
```

**Comment by jlaneve** [comment]
How do you define your keyfile in Airflow? Do you mind sharing your connection structure?

**Comment by CorsettiS** [comment]
Here it goes
![Uploading Screenshot 2023-06-26 at 20.16.25.png…]()

the keyfile JSON is being passed directly

**Comment by jlaneve** [comment]
ahh -  we don't yet support keyfile JSON, just a path to the keyfile. that could be a good first contribution, though!

**Comment by CorsettiS** [comment]
@jlaneve I will try to properly set up my local env with the newest version and see if I can contribute on that then :) thanks for the help !
