### ISSUE TITLE
Dbt done but comos mark it is a fail run.

### ISSUE THREAD

**Issue by binhnq94** [astronomer/astronomer-cosmos#521]
Dbt done itself but comos mark it is a fail run.
Vesions:
- dbt==1.6.2
- postgres==1.6.2
- astronomer-cosmos: master branch.

The log generated by `customers_run` is bellow:

```
*** Reading local file: /usr/local/airflow/logs/dag_id=basic_cosmos_dag/run_id=scheduled__2023-09-07T00:00:00+00:00/task_id=customers.customers_run/attempt=1.log
[2023-09-08, 10:14:46 +07] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: basic_cosmos_dag.customers.customers_run scheduled__2023-09-07T00:00:00+00:00 [queued]>
[2023-09-08, 10:14:46 +07] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: basic_cosmos_dag.customers.customers_run scheduled__2023-09-07T00:00:00+00:00 [queued]>
[2023-09-08, 10:14:46 +07] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-09-08, 10:14:46 +07] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-09-08, 10:14:46 +07] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-09-08, 10:14:47 +07] {taskinstance.py:1300} INFO - Executing <Task(DbtRunLocalOperator): customers.customers_run> on 2023-09-07 00:00:00+00:00
[2023-09-08, 10:14:47 +07] {standard_task_runner.py:55} INFO - Started process 2739 to run task
[2023-09-08, 10:14:47 +07] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'basic_cosmos_dag', 'customers.customers_run', 'scheduled__2023-09-07T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/basic_cosmos_dag.py', '--cfg-path', '/tmp/tmpi9tpv2yi']
[2023-09-08, 10:14:47 +07] {standard_task_runner.py:83} INFO - Job 51: Subtask customers.customers_run
[2023-09-08, 10:14:47 +07] {task_command.py:388} INFO - Running <TaskInstance: basic_cosmos_dag.customers.customers_run scheduled__2023-09-07T00:00:00+00:00 [running]> on host e5f9301841cc
[2023-09-08, 10:14:47 +07] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=basic_cosmos_dag
AIRFLOW_CTX_TASK_ID=customers.customers_run
AIRFLOW_CTX_EXECUTION_DATE=2023-09-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-07T00:00:00+00:00
[2023-09-08, 10:14:47 +07] {local.py:173} INFO - Cloning project to writable temp directory /tmp/tmphjjrswnm from /usr/local/airflow/dags/dbt/jaffle_shop
[2023-09-08, 10:14:47 +07] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2023-09-08, 10:14:47 +07] {subprocess.py:73} INFO - Running command: ['/usr/local/bin/dbt', 'deps']
[2023-09-08, 10:14:47 +07] {subprocess.py:84} INFO - Command output:
[2023-09-08, 10:14:48 +07] {subprocess.py:94} INFO - [0m03:14:48  Running with dbt=1.6.2
[2023-09-08, 10:14:49 +07] {subprocess.py:94} INFO - [0m03:14:49  Installing dbt-labs/dbt_utils
[2023-09-08, 10:14:50 +07] {subprocess.py:94} INFO - [0m03:14:50  Installed from version 1.1.1
[2023-09-08, 10:14:50 +07] {subprocess.py:94} INFO - [0m03:14:50  Up to date!
[2023-09-08, 10:14:52 +07] {subprocess.py:98} INFO - Command exited with return code 0
[2023-09-08, 10:14:52 +07] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-09-08, 10:14:52 +07] {base.py:73} INFO - Using connection ID 'airflow_db' for task execution.
[2023-09-08, 10:14:52 +07] {base.py:147} INFO - Using real values for profile default
[2023-09-08, 10:14:52 +07] {config.py:168} INFO - Creating temporary profiles.yml at /tmp/tmp6igiwe_i/profiles.yml with the following contents:
default:
    outputs:
        dev:
            dbname: airflow
            host: postgres
            password: '{{ env_var(''COSMOS_CONN_POSTGRES_PASSWORD'') }}'
            port: 5432
            schema: public
            type: postgres
            user: airflow
    target: dev

[2023-09-08, 10:14:52 +07] {local.py:205} INFO - Trying to run the command:
 ['/usr/local/bin/dbt', 'run', '--models', 'customers', '--profiles-dir', '/tmp/tmp6igiwe_i', '--profile', 'default', '--target', 'dev']
From /tmp/tmphjjrswnm/dbt_project
[2023-09-08, 10:14:52 +07] {local.py:206} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID', 'COSMOS_CONN_POSTGRES_PASSWORD'])
[2023-09-08, 10:14:52 +07] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2023-09-08, 10:14:52 +07] {subprocess.py:73} INFO - Running command: ['/usr/local/bin/dbt', 'run', '--models', 'customers', '--profiles-dir', '/tmp/tmp6igiwe_i', '--profile', 'default', '--target', 'dev']
[2023-09-08, 10:14:52 +07] {subprocess.py:84} INFO - Command output:
[2023-09-08, 10:14:53 +07] {subprocess.py:94} INFO - [0m03:14:53  Running with dbt=1.6.2
[2023-09-08, 10:14:53 +07] {subprocess.py:94} INFO - [0m03:14:53  Registered adapter: postgres=1.6.2
[2023-09-08, 10:14:53 +07] {subprocess.py:94} INFO - [0m03:14:53  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  Found 5 models, 3 seeds, 20 tests, 0 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  Concurrency: 1 threads (target='dev')
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  1 of 1 START sql table model public.customers .................................. [RUN]
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  1 of 1 ERROR creating sql table model public.customers ......................... [[31mERROR[0m in 0.11s]
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  Finished running 1 table model in 0 hours 0 minutes and 0.20 seconds (0.20s).
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  [31mCompleted with 1 error and 0 warnings:[0m
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54    Database Error in model customers (models/customers.sql)
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO -   improper relation name (too many dotted names): public.airflow.public.customers__dbt_backup
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO -   compiled Code at target/run/jaffle_shop/models/customers.sql
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54
[2023-09-08, 10:14:54 +07] {subprocess.py:94} INFO - [0m03:14:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-09-08, 10:14:57 +07] {subprocess.py:98} INFO - Command exited with return code 1
[2023-09-08, 10:14:57 +07] {local.py:222} INFO - Inlets: []
[2023-09-08, 10:14:57 +07] {local.py:223} INFO - Outlets: []
[2023-09-08, 10:14:57 +07] {dag.py:2690} INFO - Sync 1 DAGs
[2023-09-08, 10:14:57 +07] {dag.py:3437} INFO - Setting next_dagrun for basic_cosmos_dag to 2023-09-08T00:00:00+00:00, run_after=2023-09-09T00:00:00+00:00
[2023-09-08, 10:14:57 +07] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 329, in execute
    self.build_and_run_cmd(context=context)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 325, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 226, in run_command
    self.exception_handling(result)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 107, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m03:14:53  Running with dbt=1.6.2', '\x1b[0m03:14:53  Registered adapter: postgres=1.6.2', '\x1b[0m03:14:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m03:14:54  Found 5 models, 3 seeds, 20 tests, 0 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models', '\x1b[0m03:14:54', "\x1b[0m03:14:54  Concurrency: 1 threads (target='dev')", '\x1b[0m03:14:54', '\x1b[0m03:14:54  1 of 1 START sql table model public.customers .................................. [RUN]', '\x1b[0m03:14:54  1 of 1 ERROR creating sql table model public.customers ......................... [\x1b[31mERROR\x1b[0m in 0.11s]', '\x1b[0m03:14:54', '\x1b[0m03:14:54  Finished running 1 table model in 0 hours 0 minutes and 0.20 seconds (0.20s).', '\x1b[0m03:14:54', '\x1b[0m03:14:54  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m03:14:54', '\x1b[0m03:14:54    Database Error in model customers (models/customers.sql)', '  improper relation name (too many dotted names): public.airflow.public.customers__dbt_backup', '  compiled Code at target/run/jaffle_shop/models/customers.sql', '\x1b[0m03:14:54', '\x1b[0m03:14:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2023-09-08, 10:14:57 +07] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=basic_cosmos_dag, task_id=customers.customers_run, execution_date=20230907T000000, start_date=20230908T031446, end_date=20230908T031457
[2023-09-08, 10:14:57 +07] {standard_task_runner.py:100} ERROR - Failed to execute job 51 for task customers.customers_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m03:14:53  Running with dbt=1.6.2', '\x1b[0m03:14:53  Registered adapter: postgres=1.6.2', '\x1b[0m03:14:53  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m03:14:54  Found 5 models, 3 seeds, 20 tests, 0 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models', '\x1b[0m03:14:54', "\x1b[0m03:14:54  Concurrency: 1 threads (target='dev')", '\x1b[0m03:14:54', '\x1b[0m03:14:54  1 of 1 START sql table model public.customers .................................. [RUN]', '\x1b[0m03:14:54  1 of 1 ERROR creating sql table model public.customers ......................... [\x1b[31mERROR\x1b[0m in 0.11s]', '\x1b[0m03:14:54', '\x1b[0m03:14:54  Finished running 1 table model in 0 hours 0 minutes and 0.20 seconds (0.20s).', '\x1b[0m03:14:54', '\x1b[0m03:14:54  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m03:14:54', '\x1b[0m03:14:54    Database Error in model customers (models/customers.sql)', '  improper relation name (too many dotted names): public.airflow.public.customers__dbt_backup', '  compiled Code at target/run/jaffle_shop/models/customers.sql', '\x1b[0m03:14:54', '\x1b[0m03:14:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 2739)
[2023-09-08, 10:14:57 +07] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-09-08, 10:14:57 +07] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by binhnq94** [comment]
Dbt return code 1. => Close issue.
