### ISSUE TITLE
After update to 1.1.0 airflow tasks fail when target-path not specified in dbt-project.yml

### ISSUE THREAD

**Issue by blthree** [astronomer/astronomer-cosmos#533]
After updating astronomer-cosmos to 1.10 from 1.05, we noticed that all of our tasks using the DBT operators (We are only using `DbtSnapshotVirtualenvOperator` right now) from cosmos were showing as failed in airflow. However, looking at the logs showed that the `dbt snapshot` command succeeded, but the subsequent Dataset creation by openlineage failed.

There's [already an issue](https://github.com/OpenLineage/OpenLineage/issues/2093) about this on the openlineage repo. The TLDR is that openlineage expects target-path to set in dbt-project.yml, but [setting target-path this way has been deprecated since dbt v1.5](https://docs.getdbt.com/reference/project-configs/target-path#configuration), 

When I get a chance, I will test to be sure, but I think this bug in openlineage will cause a simple `dbt init jaffle_shop` aka "hello world" type dbt project to fail when run using cosmos+airflow when using dbt>=1.5, beacuse creating a new dbt project via `dbt init` the auto-generated dbt_project.yml does not contain a target-path property after v1.5 and it looks like cosmos defaults to `emit_datasets=True`.

I will try to work up a very simple repro dbt project (hopefully just jaffleshop), but I think the problem will be triggered anytime one of the cosmos 1.10 operators with emit_datasets=True is run against a dbt project missing `target-path` in dbt-project.yml.

My temporary workaround will be to add `target-path` back into my dbt-project.yml, which it appears dbt 1.6 is still allowing.

Relevant logs from airflow:
```
[2023-09-13, 10:10:04 EDT] {subprocess.py:73} INFO - Running command: ['/tmp/cosmos-venv0xaea_yi/bin/dbt', 'snapshot', '--models', '<MODELNAME>', '--profiles-dir', '/tmp/tmpu380zu1l', '--profile', 'default', '--target', 'dev']
[2023-09-13, 10:10:04 EDT] {subprocess.py:84} INFO - Command output:
[2023-09-13, 10:10:08 EDT] {subprocess.py:94} INFO - [0m14:10:08  Running with dbt=1.6.2
[2023-09-13, 10:10:08 EDT] {subprocess.py:94} INFO - [0m14:10:08  Registered adapter: redshift=1.6.0
[2023-09-13, 10:10:08 EDT] {subprocess.py:94} INFO - [0m14:10:08  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2023-09-13, 10:10:12 EDT] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: <DAG ID>.<TaskGroup ID>.<Task ID> scheduled__2023-09-12T14:00:00+00:00 [running]> from DB
[2023-09-13, 10:10:13 EDT] {subprocess.py:94} INFO - [0m14:10:13  Found 5 models, 12 snapshots, 2 tests, 13 sources, 0 exposures, 0 metrics, 761 macros, 0 groups, 0 semantic models
[2023-09-13, 10:10:13 EDT] {subprocess.py:94} INFO - [0m14:10:13
[2023-09-13, 10:10:15 EDT] {subprocess.py:94} INFO - [0m14:10:15  Concurrency: 1 threads (target='dev')
[2023-09-13, 10:10:15 EDT] {subprocess.py:94} INFO - [0m14:10:15
[2023-09-13, 10:10:15 EDT] {subprocess.py:94} INFO - [0m14:10:15  1 of 1 START snapshot <MODELNAME> .................. [RUN]
[2023-09-13, 10:10:17 EDT] {subprocess.py:94} INFO - [0m14:10:17  Running custom snapshot_snapshot_staging_table
[2023-09-13, 10:10:17 EDT] {subprocess.py:94} INFO - [0m14:10:17  Running custom snapshot_staging_table with hard deletes
[2023-09-13, 10:10:48 EDT] {subprocess.py:94} INFO - [0m14:10:48  Running custom snapshot_merge_sql
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50  1 of 1 OK snapshotted <MODELNAME> .................. [[32mSUCCESS[0m in 34.80s]
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50  Finished running 1 snapshot in 0 hours 0 minutes and 36.88 seconds (36.88s).
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50  [32mCompleted successfully[0m
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50
[2023-09-13, 10:10:50 EDT] {subprocess.py:94} INFO - [0m14:10:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-09-13, 10:10:51 EDT] {subprocess.py:98} INFO - Command exited with return code 0
[2023-09-13, 10:10:51 EDT] {configuration.py:1064} WARNING - section/key [openlineage/namespace] not found in config
[2023-09-13, 10:10:51 EDT] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 95, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 338, in execute
    self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 334, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 217, in run_command
    self.calculate_openlineage_events_completes(env, Path(tmp_project_dir))
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 260, in calculate_openlineage_events_completes
    openlineage_processor = DbtLocalArtifactProcessor(
  File "/home/airflow/.local/lib/python3.10/site-packages/openlineage/common/provider/dbt/local.py", line 58, in __init__
    absolute_dir, dbt_project["target-path"], "manifest.json"
KeyError: 'target-path'
```

**Comment by tatiana** [comment]
Thank you very much for this bug report, @blthree ! We need to improve our integration tests with virtualenv. We'll do our best to fix this as part of Cosmos 1.1.2

**Comment by tatiana** [comment]
@blthree the fix was merged yesterday in OpenLineage and released as part of 1.2:
https://pypi.org/project/openlineage-integration-common/1.2.0/

openlineage-integration-common>=1.2.0

**Comment by blthree** [comment]
Thanks for the quick response!

**Comment by PrimOox** [comment]
i am having this error, but i do not use OpenLineage
