### ISSUE TITLE
Fix DbtTestOperator openlineage-integration-common issue when test does not have `test_metadata`

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#545]
Issue reported in the Slack #airflow-dbt channel by Javier Hernández Novoa, on the `DbtTestOperator`:

https://apache-airflow.slack.com/archives/C059CC42E9W/p1695067128727239

```
[2023-09-18, 19:54:12 UTC] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 360, in execute
    self.build_and_run_cmd(context=context)
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 356, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 230, in run_command
    self.calculate_openlineage_events_completes(env, Path(tmp_project_dir))
  File "/usr/local/lib/python3.11/site-packages/cosmos/operators/local.py", line 278, in calculate_openlineage_events_completes
    events = openlineage_processor.parse()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openlineage/common/provider/dbt/processor.py", line 211, in parse
    events += self.parse_test(context, nodes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openlineage/common/provider/dbt/processor.py", line 308, in parse_test
    assertions = self.parse_assertions(context, nodes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openlineage/common/provider/dbt/processor.py", line 367, in parse_assertions
    assertion=test_node["test_metadata"]["name"],
              ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'test_metadata'
```

This issue is similar to https://github.com/OpenLineage/OpenLineage/issues/2093.

Two actions, that can be split in two tickets as well:
* [ ] Fix on the Openlineage library
* [ ] Fix on Cosmos, so we are more resilient to this type of error: https://github.com/astronomer/astronomer-cosmos/blob/27d1945557d33e31469661043915b089333e5f66/cosmos/operators/local.py#L280

**Comment by tatiana** [comment]
The fix was released as part of **astronomer-cosmos 1.1.2:**
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.1.2
* https://pypi.org/project/astronomer-cosmos/1.1.2/
