### ISSUE TITLE
Improve error handling when using astro-cli and running dbt deps to render DAG

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#593]
A user trying out Cosmos 1.1.3 and astro-cli reported the following issue in the #airflow-dbt slack:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1696942075155009

This stack trace shows that issues were running `dbt deps` in the container:

```
Broken DAG: [/usr/local/airflow/dags/titi3.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 121, in load
    self.load_via_dbt_ls()
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 203, in load_via_dbt_ls
    raise CosmosLoadDbtException(f"Unable to run dbt deps command due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run dbt deps command due to the error:
[0m08:35:04  Running with dbt=1.4.9
[0m08:35:07  Installing https://github.com/fishtown-analytics/dbt-utils.git
[0m08:35:08  Encountered an error:
[Errno 13] Permission denied: 'branches'
[0m08:35:08  Traceback (most recent call last):
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/main.py", line 253, in run_from_args
    results = task.run()
              ^^^^^^^^^^
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/task/deps.py", line 75, in run
    package.install(self.config, renderer)
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/deps/git.py", line 93, in install
    system.rmdir(dest_path)
  File "/usr/local/airflow/dbt_venv/lib/python3.11/site-packages/dbt/clients/system.py", line 227, in rmdir
    shutil.rmtree(path, onerror=onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/lib/python3.11/shutil.py", line 666, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/local/lib/python3.11/shutil.py", line 664, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'branches'
```

As seen in the thread, to set `RenderConfig. dbt_deps` to `False` solved the issue.

I was surprised by this error since we implemented https://github.com/astronomer/astronomer-cosmos/pull/414. It would be great to investigate it further.

If we can't fix the source issue due to user permissions, we could capture this type of exception and give the user a warning message suggesting they set  `RenderConfig. dbt_deps` to `False`.

**Comment by tatiana** [comment]
@jlaneve suggested we could set `dbt_deps` to True by default, which sounds a good idea! This way Cosmos will be consistent (`LoadMethod.DBT_LS` and operator's exposing environment variables).
