### ISSUE TITLE
dbt ls fails on "Error" string in stdout

### ISSUE THREAD

**Issue by adammarples** [astronomer/astronomer-cosmos#642]
This error check https://github.com/astronomer/astronomer-cosmos/blob/635fb7badfd1fea560923d3f959ab7d021dba83d/cosmos/dbt/graph.py#L253C1-L255C111

```python
if returncode or "Error" in stdout:
    details = stderr or stdout
    raise CosmosLoadDbtException(f"Unable to run dbt ls command due to the error:\n{details}")
```

Causes a failure when stdout includes (in my example)

```python-traceback
Broken DAG: [/usr/local/airflow/dags/playground.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 132, in load
    load_method[method]()
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 255, in load_via_dbt_ls
    raise CosmosLoadDbtException(f"Unable to run dbt ls command due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run dbt ls command due to the error:
[0m12:48:41  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff85fc0110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff860efe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff85dfbc90>]}
[0m12:48:41  Running with dbt=1.6.7
[0m12:48:41  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'True', 'profiles_dir': '/tmp/tmp1v3xloax', 'log_path': '/tmp/tmp6rmp2huk/logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt ls --output json --exclude tag:qc_test --select stage --project-dir /tmp/tmp6rmp2huk --profiles-dir /tmp/tmp1v3xloax --profile vulcan_profile --target pr', 'target_path': '/tmp/tmp6rmp2huk/target', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
```

Specifically "Error" is being found in the last line here

```python
'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])'
```

This check is overly broad and doesn't even allow people to have ie. directories or model names with "Error" in them.

**Comment by tatiana** [comment]
Hi @adammarples, I'm sorry you're facing this issue. I fully agree we need to improve this.

This was introduced because the `dbt` may times raise errors, but without using the adequate OS process return code.

Would you like to contribute to improving this part of Cosmos?

**Comment by adammarples** [comment]
I would love to help, it sounds like an issue with dbt-core primarily though. Do you have any info about when these errors occur without adequate returncodes or why you started searching for the "Error" string in the first place? Thanks

**Comment by tatiana** [comment]
@adammarples, I agree that, ideally, this would be resolved in dbt itself.

The dbt documentation states the exit code would be 0 only if the dbt invocation is completed without error:
https://docs.getdbt.com/reference/exit-codes

However, it seems there was a decision to have dbt ls always return 0, which is not compatible with the documentation:
https://github.com/dbt-labs/dbt-core/pull/2892

I remember two scenarios when we needed to capture errors raised while running `dbt ls`:
1. When there were missing adapters: https://github.com/astronomer/astronomer-cosmos/issues/445
2. If using a user-defined `profiles.yml` that contained references to unset environment variables

**Comment by adammarples** [comment]
As a workaround, I wonder if something like 

```python
if returncode or "Error" in stdout.replace("WarnErrorOptions", ""):
```
Would be acceptable because I suspect that WarnErrorOptions is going to turn up a lot

**Comment by tatiana** [comment]
@adammarples yes, I believe this would be a valid workaround - would you like to make this contribution to Cosmos?

**Comment by adammarples** [comment]
> @adammarples yes, I believe this would be a valid workaround - would you like to make this contribution to Cosmos?

would be happy to

**Comment by adammarples** [comment]
@tatiana https://github.com/astronomer/astronomer-cosmos/pull/692

**Comment by tatiana** [comment]
@adammarples Since we've released the workaround in 1.2.5 and don't have a better solution now, I'm closing this ticket. Please, feel free to reopen or open a new one if you have any suggestions of how we could better handle this.

**Comment by adammarples** [comment]
@tatiana actually I think I have a very simple workaround for this if it isn't fixed in dbt-core. We can force specific warnings to become errors for the `dbt ls` command and force them to return exit code 2. 

For example, to raise an error for the issue that dbt-core were initially trying to fix, [no nodes selected on dbt ls](https://github.com/dbt-labs/dbt-core/issues/2886), we could catch that warning and turn it into an error when running ls.

```python
dbt --warn-error-options '{"include": ["NoNodesForSelectionCriteria"]}' ls 
```

For the issues you mentioned:

1. When there were missing adapters: https://github.com/astronomer/astronomer-cosmos/issues/445
2. If using a user-defined profiles.yml that contained references to unset environment variables

I tested 2 and it actually already returns an error code 2. I'm not sure what 1 exactly is, but it seems to be the same env_vars issue?
