### ISSUE TITLE
Setting `operator_args.env` not injecting properly with `ExecutionMode.LOCAL`

### ISSUE THREAD

**Issue by yoyomeng2** [astronomer/astronomer-cosmos#646]
## Summary
I have a scaling issue when running with `ExecutionMode.VIRTUALENV` (MWAA disk is filling) so I'm attempting to use `LOCAL`.

My current dbt profile uses `private_key_path` and `private_key_passphrase` like so:
```yaml
      private_key_path: /tmp/rsa_key.p8
      private_key_passphrase: '{{ env_var("PRIVATE_KEY_PASSPHRASE") }}'
```

I provide this passphrase to dbt and write the key file in my DAG:
```python
PRIVATE_KEY_PASSPHRASE = Variable.get("private_key_passphrase", default_var=None)
ENCRYPTED_PRIVATE_KEY_CONTENT = Variable.get("encrypted_private_key", default_var=None)
EXECUTION_CONFIG = ExecutionConfig(execution_mode=ExecutionMode.VIRTUALENV)
OPERATOR_ARGS = {
    "env": {
        "PRIVATE_KEY_PASSPHRASE": PRIVATE_KEY_PASSPHRASE,
    },
}

@dag()
def run_dag():
    with open("/tmp/rsa_key.p8", "w") as f:
        f.write(ENCRYPTED_PRIVATE_KEY_CONTENT)

   seed_data = DbtTaskGroup(
        group_id="seed_data",
        project_config=PROJECT_CONFIG,
        profile_config=PROFILE_CONFIG,
        execution_config=EXECUTION_CONFIG,
        operator_args=OPERATOR_ARGS,
        render_config=RenderConfig(
            select = ["path:seeds"],
            dbt_deps=False
        ),
    )
```

This works nicely until MWAA disk fills. When switching to `ExecutionMode.LOCAL` to avoid creating a temporary virtual environment per task a DAG Import Error occurs.

## Observed Behavior

When running in `ExecutionMode.LOCAL` this DAG Import Error occurs.
```
Broken DAG: [/usr/local/airflow/dags/cosmos_dag_bare.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 120, in load
    self.load_via_dbt_ls()
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 241, in load_via_dbt_ls
    raise CosmosLoadDbtException(f"Unable to run dbt ls command due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run dbt ls command due to the error:
[0m22:42:41  Running with dbt=1.5.2
[0m22:42:41  Encountered an error:
Parsing Error
  Env var required but not provided: 'PRIVATE_KEY_PASSPHRASE'
```

## Expected Behavior

The environment variable is injected the same as with `ExecutionMode.VIRTUALENV`.

## Reproducing

Using Astro CLI v9.4.0

requirements.txt:
```
# Astro Runtime includes the following pre-installed providers packages: https://docs.astronomer.io/astro/runtime-image-architecture#provider-packages
apache-airflow-providers-snowflake==4.4.2
dbt-core == 1.5.2
dbt-snowflake == 1.5.1
astronomer-cosmos==1.1.1
```
A `profiles.yml` like:
```yaml
project_profile:
  target: sandbox
  outputs:
    sandbox_pk:
      user: <user>
      private_key_path: /tmp/rsa_key.p8
      role: <role>
      database: <database
      warehouse: <warehouse
      schema: <schema>
      query_tag: sa-dbt-project-template
      private_key_passphrase: '{{ env_var("PRIVATE_KEY_PASSPHRASE") }}'

      type: snowflake
      account: <account>
      client_session_keep_alive: False
      reuse_connections: True
      threads: 1
```

A dag that writes the key content to a file and passes the env var like:
```python
import os
from datetime import datetime, timedelta

from airflow.decorators import dag
from airflow.models import Variable
from airflow.operators.empty import EmptyOperator
from cosmos import DbtTaskGroup, ExecutionConfig, ExecutionMode, ProjectConfig, ProfileConfig, RenderConfig


DBT_PROJECT_FOLDER_NAME="jaffle_shop"
DAG_ID = os.path.basename(__file__).replace(".py", "")
ENV = Variable.get("environment", default_var="sandbox")
DEFAULT_ARGS = {
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
}
VIRTUAL_ENV_PACKAGES = [
    "dbt-core==1.5.2",
    "dbt-snowflake==1.5.1",
]
DBT_PROJECT_DIR = f"/usr/local/airflow/dags/dbt/models/{DBT_PROJECT_FOLDER_NAME}"
DBT_PROFILES_DIR = f"/usr/local/airflow/dags/dbt/models/{DBT_PROJECT_FOLDER_NAME}/profiles.yml"
PROJECT_CONFIG = ProjectConfig(
    dbt_project_path=DBT_PROJECT_DIR,
    models_relative_path="models",
    seeds_relative_path="seeds",
    snapshots_relative_path="snapshots",
)
PRIVATE_KEY_PASSPHRASE = Variable.get("private_key_passphrase", default_var=None)
ENCRYPTED_PRIVATE_KEY_CONTENT = Variable.get("encrypted_private_key", default_var=None)
PROFILE_CONFIG = ProfileConfig(
    profile_name="project_profile", target_name=f"{ENV}_pk", profiles_yml_filepath=DBT_PROFILES_DIR
)

EXECUTION_CONFIG = ExecutionConfig(execution_mode=ExecutionMode.LOCAL)
OPERATOR_ARGS = {
            "py_system_site_packages": False,
            "py_requirements": VIRTUAL_ENV_PACKAGES,
            "install_deps": False,
            "env": {"PRIVATE_KEY_PASSPHRASE": PRIVATE_KEY_PASSPHRASE},
        }

@dag(
    dag_id=DAG_ID,
    description=f"DAG to run dbt models for {DBT_PROJECT_FOLDER_NAME}",
    start_date=datetime(2023, 10, 21),
    schedule_interval=None,
    default_args=DEFAULT_ARGS,
    dagrun_timeout=timedelta(hours=1),
    max_active_runs=1,
    catchup=False,
    tags=["dbt", DBT_PROJECT_FOLDER_NAME, "SNOWFLAKE"],
)
def run():
    with open("/tmp/rsa_key.p8", "w") as f:
        f.write(ENCRYPTED_PRIVATE_KEY_CONTENT)

    seed_data = DbtTaskGroup(
        group_id="seed_data",
        project_config=PROJECT_CONFIG,
        profile_config=PROFILE_CONFIG,
        execution_config=EXECUTION_CONFIG,
        operator_args=OPERATOR_ARGS,
        render_config=RenderConfig(select = ["path:seeds"], dbt_deps=False),
    )

    task_start = EmptyOperator(task_id="start")

    task_end = EmptyOperator(task_id="end")

    task_start >> seed_data >> task_end


run()

```

**Comment by tatiana** [comment]
@yoyomeng2, thanks for the fantastic description!

Please confirm if the error also happens for the latest Cosmos release, 1.2.1.

It would be great to have more details on the disk filling up when using `LoadMode.VIRTUALENV` - is the disk usage increasing each time a DAG is run / tasks are executed, or is it just the expected virtualenv creation during task execution?

**Comment by yoyomeng2** [comment]
@tatiana I think this might be related: https://github.com/astronomer/astronomer-cosmos/issues/550

I haven't analyzed much why `ExecutionMode.VIRTUALENV` is filling MWAA. Currently I assume it is related to scale because we weren't seeing this until multiple dbt projects were introduced.
