### ISSUE TITLE
load_via_dbt_ls() requires dbt is installed in base airflow environment

### ISSUE THREAD

**Issue by dylanharper-qz** [astronomer/astronomer-cosmos#670]
Apologies if I'm misunderstanding anything here, we're big fans of Cosmos at Quizlet.

In version 1.2.2, we are seeing this error when using `LoadMode.DBT_LS`:
```
Broken DAG: [/usr/local/airflow/dags/my_dbt_hourly.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 184, in load
    load_method[method]()
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 233, in load_via_dbt_ls
    raise CosmosLoadDbtException(f"Unable to find the dbt executable: {self.dbt_cmd}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to find the dbt executable: dbt
```

If we add dbt to our default airflow environment, the dag works as expected.

It is required to install dbt outside of the venv described in the docs?

This code seems to be checking for dbt in the airflow environment: https://github.com/astronomer/astronomer-cosmos/blob/6e41471712d9352524e70a59a1380e8e52c5ede2/cosmos/dbt/graph.py#L232-L233

**Comment by dylanharper-qz** [comment]
@dosu-bot I have confirmed that setting `dbt_executable_path` in the `RenderConfig` resolved this issue.

Thank you, you have been very helpful.
