### ISSUE TITLE
shutil.copytree fails in local.py run_command

### ISSUE THREAD

**Issue by adammarples** [astronomer/astronomer-cosmos#689]
astronomer-cosmos==0.7.3

I periodically get failures like this when running a simple `dbt run --models` on a local operator.

```python-traceback
2023-11-17T12:29:09.6922654Z Traceback (most recent call last):
2023-11-17T12:29:09.6923817Z   File "/usr/local/lib/python3.11/site-packages/cosmos/providers/dbt/core/operators/local.py", line 323, in execute
2023-11-17T12:29:09.6924959Z     result = self.build_and_run_cmd(context=context)
2023-11-17T12:29:09.6925513Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-17T12:29:09.6926833Z   File "/usr/local/lib/python3.11/site-packages/cosmos/providers/dbt/core/operators/local.py", line 235, in build_and_run_cmd
2023-11-17T12:29:09.6928139Z     return self.run_command(cmd=dbt_cmd, env=env, context=context)
2023-11-17T12:29:09.6928940Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-17T12:29:09.6930205Z   File "/usr/local/lib/python3.11/site-packages/cosmos/providers/dbt/core/operators/local.py", line 183, in run_command
2023-11-17T12:29:09.6931313Z     shutil.copytree(
2023-11-17T12:29:09.6931849Z   File "/usr/local/lib/python3.11/shutil.py", line 561, in copytree
2023-11-17T12:29:09.6932703Z     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
2023-11-17T12:29:09.6933426Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-17T12:29:09.6934128Z   File "/usr/local/lib/python3.11/shutil.py", line 515, in _copytree
2023-11-17T12:29:09.6934800Z     raise Error(errors)
2023-11-17T12:29:09.6937525Z shutil.Error: [('/usr/local/airflow/dags/dbt/vulcan/tests/generic/qc/.my_test.md.EDIhpJ', '/tmp/tmplbyb8o0q/dbt_project/tests/generic/qc/.my_test.md.EDIhpJ', "[Errno 2] No such file or directory: '/usr/local/airflow/dags/dbt/vulcan/tests/generic/qc/.my_test.md.EDIhpJ'")]
2023-11-17T12:29:09.6942173Z [2023-11-17T12:23:57.364+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=azure_ci_end_to_end, task_id=azure_ci_end_to_end_stage.TABLE.TABLE_run, execution_date=20231117T121825, start_date=20231117T122356, end_date=20231117T122357
2023-11-17T12:29:09.6948352Z [2023-11-17T12:23:57.957+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 73 for task azure_ci_end_to_end_stage.TABLE.TABLE_run ([('/usr/local/airflow/dags/dbt/vulcan/tests/generic/qc/.my_test.md.EDIhpJ', '/tmp/tmplbyb8o0q/dbt_project/tests/generic/qc/.my_test.md.EDIhpJ', "[Errno 2] No such file or directory: '/usr/local/airflow/dags/dbt/vulcan/tests/generic/qc/.my_test.md.EDIhpJ'")]; 66)
```

In this instance it is failing to copy a test documentation file called my_test.md but it happens with model files and others too.

The issue is that run_command calls shutil.copytree to copy the contents of the project directory. This fails when it says that a source file doesn't exist. This is odd for two reasons.

1) shutil.copytree shouldn't be attempting to move files which don't exist, which means that the files are being modified while it is running. I think it has something to do with this https://github.com/astronomer/astronomer-cosmos/issues/226 because I do have two task groups chained together.

2) The files have dot prefixes and random suffixes like `.my_test.md.EDIhpJ` which suggest that they are tempfiles or partial files.

I suspect that the answer will be to upgrade to the latest version but I am hesitant to do so because last time I ran into this issue https://github.com/astronomer/astronomer-cosmos/issues/642

Would very much appreciate a hint on what is happening and maybe I could fix it.

**Comment by tatiana** [comment]
@adammarples is there any particular reason why you're using `astronomer-cosmos==0.7.3`, and not the latest releases (we're currently at `astronomer-cosmos==1.2.4`?

**Comment by adammarples** [comment]
@tatiana the reason I'm not updating from 0.7.3 to latest is because the signature for DbtTaskGroup has changed and it would involve some new coding and testing. In my tests in upgrading to the latest version I have run into issues #642 #693 #694 which has made it impossible for me to use the select methods that I need in this case
