### ISSUE TITLE
Issue running non kubernetes gives kurbetes error

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#729]
I'm using cosmos without kubernetes yet the logs are outputting errors related to kubernetes.

```
Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 23, in <module>
    from airflow.providers.cncf.kubernetes.backcompat.backwards_compat_converters import (
ModuleNotFoundError: No module named 'airflow.providers.cncf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 31, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf'
[2023-11-30 12:57:36,961] {kubernetes.py:33} ERROR - No module named 'airflow.providers.cncf'
Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 23, in <module>
    from airflow.providers.cncf.kubernetes.backcompat.backwards_compat_converters import (
ModuleNotFoundError: No module named 'airflow.providers.cncf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 31, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf'
[2023-11-30 12:57:36,961] {kubernetes.py:33} ERROR - (astronomer-cosmos) - No module named 'airflow.providers.cncf'
Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 23, in <module>
    from airflow.providers.cncf.kubernetes.backcompat.backwards_compat_converters import (
ModuleNotFoundError: No module named 'airflow.providers.cncf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\u236618\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cosmos\operators\kubernetes.py", line 31, in <module>
    from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf'
```

**Comment by DanMawdsleyBA** [comment]
1.3.0a2 It doesn't cause an actual issue as things still run ok but it does make the logs confusing
