### ISSUE TITLE
`disable_event_tracking=True` throwing `Failed validating 'type' in schema['properties']['send_anonymous_usage_stats']`

### ISSUE THREAD

**Issue by jaredx435k2d0** [astronomer/astronomer-cosmos#783]
According to [Disabling dbt event tracking](https://astronomer.github.io/astronomer-cosmos/profiles/index.html#disabling-dbt-event-tracking), I think I'm using `disable_event_tracking` correctly:

```
profile_config = ProfileConfig(
	profile_name="analytics_profile",
	target_name="dev",
	profile_mapping=SnowflakeUserPasswordProfileMapping(
		conn_id=CONNECTION_ID,
		profile_args = {"threads": 32, "reuse_connections": True},
		disable_event_tracking=True
	),
)
```

But when I use it, I'm getting the following at the top of the dashboard in the web UI:
```
Broken DAG: [/usr/local/airflow/dags/dag_dbt_hourly.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 204, in run_dbt_ls
    stdout = run_command(ls_command, tmp_dir, env_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 94, in run_command
    raise CosmosLoadDbtException(f"Unable to run {command} due to the error:\n{details}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/usr/local/airflow/dbt__venv/bin/dbt', 'ls', '--output', 'json', '--selector', 'hourly__selector', '--project-dir', '/tmp/tmp6es6bqul', '--profiles-dir', '/tmp/tmpl8fs0omc', '--profile', 'analytics_profile', '--target', 'dev'] due to the error:
[0m19:57:43  Running with dbt=1.7.4
[0m19:57:43  Encountered an error:
'False' is not of type 'boolean'

Failed validating 'type' in schema['properties']['send_anonymous_usage_stats']:
    {'default': True, 'type': 'boolean'}

On instance['send_anonymous_usage_stats']:
    'False'
[0m19:57:43  jsonschema.exceptions.ValidationError: 'False' is not of type 'boolean'

Failed validating 'type' in schema['properties']['send_anonymous_usage_stats']:
    {'default': True, 'type': 'boolean'}

On instance['send_anonymous_usage_stats']:
    'False'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 165, in wrapper
    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/config/runtime.py", line 70, in load_profile
    profile = Profile.render(
              ^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/config/profile.py", line 436, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/config/profile.py", line 401, in from_raw_profiles
    return cls.from_raw_profile_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/config/profile.py", line 359, in from_raw_profile_info
    return cls.from_credentials(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/config/profile.py", line 265, in from_credentials
    UserConfig.validate(user_config)
  File "/usr/local/airflow/dbt__venv/lib/python3.11/site-packages/dbt/dataclass_schema.py", line 89, in validate
    raise ValidationError.create_from(error) from error
dbt.dataclass_schema.ValidationError: 'False' is not of type 'boolean'

Failed validating 'type' in schema['properties']['send_anonymous_usage_stats']:
    {'default': True, 'type': 'boolean'}

On instance['send_anonymous_usage_stats']:
    'False'
```

Do I need to use it differently?

astronomer-cosmos==1.3.0
quay.io/astronomer/astro-runtime:10.0.0

**Comment by jbandoro** [comment]
Thanks for reporting @jaredx435k2d0, I'll investigate and fix this. I think it's because I initially was using:

```yaml
config:
  send_anonymous_usage_stats: false
```
and it was working, but then noticed in the the [dbt docs](https://docs.getdbt.com/reference/global-configs/usage-stats) they had `False` which I switched it to which I think is causing the error you're seeing.
