### ISSUE TITLE
`DbtLocalArtifactProcessor` attempts to access `dbt_project["target-path"]` but `target-path` is not present in the `dbt_project dictionary`

### ISSUE THREAD

**Issue by PrimOox** [astronomer/astronomer-cosmos#861]
Having the same error as the issue #533, but i am not using OpenLineage. I am running airflow on EKS.

Setting the `target-path` in the `dbt_project.yml` is deprecated as described [in docs](https://docs.getdbt.com/reference/project-configs/target-path). I also tried to set it in `dbt_cmd_global_flags` but did not worked.

```
[2024-02-26, 12:39:55 -03] {log.py:232} WARNING - [[34m2024-02-26T15:39:55.020+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m15:39:55  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1[0m
[2024-02-26, 12:39:55 -03] {subprocess.py:94} INFO - [0m15:39:55  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-02-26, 12:39:55 -03] {log.py:232} WARNING - [[34m2024-02-26T15:39:55.521+0000[0m] {[34msubprocess.py:[0m98} INFO[0m - [35m(astronomer-cosmos)[0m - Command exited with return code 0[0m
[2024-02-26, 12:39:55 -03] {subprocess.py:98} INFO - Command exited with return code 0
[2024-02-26, 12:39:55 -03] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/root/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/root/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 244, in run_command
    self.calculate_openlineage_events_completes(env, Path(tmp_project_dir))
  File "/root/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 281, in calculate_openlineage_events_completes
    openlineage_processor = DbtLocalArtifactProcessor(
  File "/home/airflow/.local/lib/python3.8/site-packages/openlineage/common/provider/dbt/local.py", line 58, in __init__
    absolute_dir, dbt_project["target-path"], "manifest.json"
KeyError: 'target-path'
[2024-02-26, 12:39:55 -03] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_cosmos_datamarts, task_id=dm_busca_parcelas_run, execution_date=20240226T150634, start_date=20240226T153908, end_date=20240226T153955
[2024-02-26, 12:39:55 -03] {standard_task_runner.py:104} ERROR - Failed to execute job 724 for task dm_busca_parcelas_run ('target-path'; 65190)
[2024-02-26, 12:39:55 -03] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-26, 12:39:55 -03] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by PrimOox** [comment]
> Hey @PrimOox, do you mind setting the env var `OPENLINEAGE_DISABLED` to `True`? That should stop the open lineage code from running if you're not using it.

it's already setted but did not make difference

**Comment by tatiana** [comment]
@PrimOox which version of `openlineage-integration-common` do you have? This is likely to have been fixed in `openlineage-integration-common>=1.2.0`
https://github.com/astronomer/astronomer-cosmos/issues/533#issuecomment-1720907853

**Comment by PrimOox** [comment]
> @PrimOox which version of `openlineage-integration-common` do you have? This is likely to have been fixed in `openlineage-integration-common>=1.2.0` [#533 (comment)](https://github.com/astronomer/astronomer-cosmos/issues/533#issuecomment-1720907853)

openlineage-integration-common==1.9.1
openlineage-python==1.9.1
openlineage_sql==1.9.1
opentelemetry-api==1.20.0
astronomer-cosmos==1.3.2

**Comment by tatiana** [comment]
@PrimOox, there is something strange. Your stack trace has the error:
```
"/home/airflow/.local/lib/python3.8/site-packages/openlineage/common/provider/dbt/local.py", line 58, in __init__
    absolute_dir, dbt_project["target-path"], "manifest.json"
KeyError: 'target-path' 
```
I checked in multiple versions of the[ OpenLineage package](https://pypi.org/project/openlineage-integration-common) being used, and the latest version of the code does not have this code in line 58:
https://github.com/OpenLineage/OpenLineage/blob/1.9.1/integration/common/openlineage/common/provider/dbt/local.py

I tried to map to older versions; the "newest" one I could find with this was 1.1.0:
https://github.com/OpenLineage/OpenLineage/blob/1.1.0/integration/common/openlineage/common/provider/dbt/local.py

Is there any chance you're using an older version of the package `openlineage-integration-common` in your deployment? The error you're facing does look like a duplicate of #533.

Cosmos 1.3.2 uses this OpenLineage to define the inlets/outlets URIs, regardless of whether OpenLineage is enabled. As a workaround, you could set in the render config:
```
RenderConfig.emit_datasets = False
```

However, I'd love to have more details about this error - since the package version code you shared does not match the stack trace.

**Comment by tatiana** [comment]
I confirmed with @PrimOox that the file
`/home/airflow/.local/lib/python3.8/site-packages/openlineage/common
/__init__.py`

**Comment by PrimOox** [comment]
> I confirmed with @PrimOox that the file `/home/airflow/.local/lib/python3.8/site-packages/openlineage/common /__init__.py`
> 
> Contains `__version__ = "1.1.0"`
> 
> Upgrading this to a release => 1.2 will solve the issue.

in fact I had old packages that were conflicting, so I cleaned everything, re-installed and now it's working.
Also, a workaround is to set `target-path: "target"` in `dbt_project.yml` instead of `target-path: ["target"]`. But the best practice is to clean old packages.

Thanks for the help @tatiana !
