### ISSUE TITLE
Use callback in case of command failure

### ISSUE THREAD

**Issue by fabiomx** [astronomer/astronomer-cosmos#867]
As mentioned in this [Slack thread](https://apache-airflow.slack.com/archives/C059CC42E9W/p1709132816438109?thread_ts=1708614071.766919&cid=C059CC42E9W) with @jlaneve, I've built a custom local operator, based on the `DbtLocalBaseOperator`, to upload the `run_results.json` file to GCS after running the `test` command, using the `callback` parameter. 

Everything works fine if the tests are ok, but if any test fails, an Airflow exception is raised, and the `callback` is not called (https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/operators/local.py#L321-L344). 

```
[2024-02-28, 15:26:13 CET] {log.py:232} WARNING - [[34m2024-02-28T14:26:13.085+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m14:26:13  Done. PASS=114 WARN=0 ERROR=1 SKIP=0 TOTAL=115[0m
[2024-02-28, 15:26:13 CET] {subprocess.py:94} INFO - [0m14:26:13  Done. PASS=114 WARN=0 ERROR=1 SKIP=0 TOTAL=115
[2024-02-28, 15:26:14 CET] {log.py:232} WARNING - [[34m2024-02-28T14:26:14.488+0000[0m] {[34msubprocess.py:[0m98} INFO[0m - [35m(astronomer-cosmos)[0m - Command exited with return code 1[0m
[2024-02-28, 15:26:14 CET] {subprocess.py:98} INFO - Command exited with return code 1
...
[2024-02-28, 15:26:14 CET] {taskinstance.py:1826} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/operators/local.py", line 366, in execute
    self.build_and_run_cmd(context=context)
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/operators/local.py", line 361, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/operators/local.py", line 247, in run_command
    self.exception_handling(result)
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/operators/local.py", line 128, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1.
...
```

At least for the `test` command, I would still need to upload the `run_results.json` produced in the `tmp_project_dir.` even in the case of failure. Indeed, when the tests fail, it's precisely when the information from the `run_results.json` is most critical. Moreover, after the failure, I can't access the `tmp_project_dir` anymore, so I haven't been able to use the `on_failure_callback` either.

**Comment by pankajkoti** [comment]
hi @fabiomx , we recently merged PR #1389, which introduces minor changes to the existing callback functionality and will be included in the upcoming Cosmos 1.8.0 release.

To allow users to try out these changes ahead of the official release, we have prepared an alpha release. You can install it using the following link: [astronomer-cosmos 1.8.0a3](https://pypi.org/project/astronomer-cosmos/1.8.0a3/). PR #1389 also provides examples showcasing how to use this callback functionality.

For additional guidance, refer to the documentation on leveraging callbacks: [Callback Configuration](https://astronomer.github.io/astronomer-cosmos/configuration/callbacks.html). The helper functions demonstrated in the examples can be found here: [cosmos/io.py](https://github.com/astronomer/astronomer-cosmos/blob/0000f80cbdb1e137b423a9297d45380441dd8c9b/cosmos/io.py). However, you are not limited to these; you can create your own custom callback functions using these examples as a reference and pass them via the callback argument.

We would greatly appreciate any feedback you have after testing this alpha release!
