### ISSUE TITLE
Bug when using `enable_mock_profile=False` in `simple_dag.py` with 1.4.0a2

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#937]
**Steps to reproduce**

Change the [simple_dag.py](https://github.com/astronomer/cosmos-demo/blob/main/dags/basic/simple_dag.py) to use `render_config=RenderConfig(enable_mock_profile=False)` and try to run it using `astronomer-cosmos==1.4.0a2`.

This raised the exception:
```
[2024-05-02, 14:32:47 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/base.py", line 266, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 469, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 354, in run_command
    self.handle_exception(result)
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 179, in handle_exception_subprocess
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m14:32:46  Running with dbt=1.5.4', '\x1b[0m14:32:46  Registered adapter: ***=1.5.4', '\x1b[0m14:32:46  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 308 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups', '\x1b[0m14:32:46', "\x1b[0m14:32:46  Concurrency: 1 threads (target='dev')", '\x1b[0m14:32:46', '\x1b[0m14:32:46  1 of 1 START seed file dbt.raw_customers ....................................... [RUN]', '\x1b[0m14:32:46  \x1b[31mUnhandled error while executing \x1b[0m', "[Errno 2] No such file or directory: '/tmp/tmpfy3ge68x/seeds/raw_customers.csv'", '\x1b[0m14:32:46  1 of 1 ERROR loading seed file dbt.raw_customers ............................... [\x1b[31mERROR\x1b[0m in 0.01s]', '\x1b[0m14:32:46', '\x1b[0m14:32:46  Finished running 1 seed in 0 hours 0 minutes and 0.09 seconds (0.09s).', '\x1b[0m14:32:46', '\x1b[0m14:32:46  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m14:32:46', "\x1b[0m14:32:46  \x1b[33m[Errno 2] No such file or directory: '/tmp/tmpfy3ge68x/seeds/raw_customers.csv'\x1b[0m", '\x1b[0m14:32:46', '\x1b[0m14:32:46  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
```

**Acceptance criteria**

* [ ] Make sure this version of the DAG can run without issues with Cosmos 1.4

**Comment by tatiana** [comment]
This issue is reproducible when using Airflow Standalone and dbt-postgres & dbt-core 1.5.4.
